"""Generate data_bulk3.py — 100 functions, ~50K lines for v3.8.0"""
import random, string
random.seed(123)

COUNTRIES = ["USA","China","India","Japan","Germany","UK","France","Brazil","Canada","Italy",
    "Australia","Russia","South Korea","Spain","Mexico","Indonesia","Netherlands","Switzerland",
    "Sweden","Norway","Poland","Belgium","Austria","Argentina","Denmark","UAE","Singapore",
    "Malaysia","Thailand","Vietnam","Philippines","Egypt","Nigeria","South Africa","Kenya",
    "Colombia","Chile","Peru","New Zealand","Ireland","Portugal","Greece","Czech Republic",
    "Hungary","Israel","Turkey","Morocco","Ukraine","Romania","Kazakhstan","Finland"]
CITIES = ["Tokyo","Delhi","Shanghai","Sao Paulo","Mumbai","Beijing","Cairo","Dhaka","Osaka","Karachi",
    "Chongqing","Istanbul","Buenos Aires","Kolkata","Lagos","Manila","Tianjin","Rio","Lahore",
    "Bangalore","Paris","Bogota","Jakarta","Chennai","Lima","Bangkok","Seoul","London","Tehran",
    "New York","Hong Kong","Baghdad","Riyadh","Santiago","Madrid","Moscow","Kuala Lumpur","Sydney",
    "Toronto","Berlin","Mexico City","Rome","Dubai","Singapore","Vienna","Athens","Budapest",
    "Warsaw","Lisbon","Prague","Stockholm","Dublin","Amsterdam","Brussels","Milan","Barcelona"]
NAMES = ["James","John","Robert","Michael","William","David","Richard","Joseph","Thomas","Charles",
    "Alexander","Benjamin","Daniel","Matthew","Andrew","Christopher","George","Edward","Henry",
    "Nicholas","Samuel","Ryan","Jacob","Ethan","Noah","Liam","Oliver","Elijah","Lucas","Mason",
    "Logan","Jack","Owen","Gabriel","Julian","Isaac","Levi","Mohammed","Omar","Hassan","Ali",
    "Ahmed","Yusuf","Wei","Jun","Li","Chen","Zhang","Liu","Hiroshi","Takashi","Kenji","Satoshi",
    "Raj","Arjun","Vikram","Ravi","Sanjay","Amit","Deepak","Rahul","Anil","Suresh","Pierre",
    "Jean","Louis","Philippe","Carlos","Jose","Miguel","Alejandro","Manuel","Jesus","Antonio"]
NAMES_F = ["Mary","Patricia","Jennifer","Linda","Barbara","Elizabeth","Susan","Jessica","Sarah",
    "Karen","Emma","Olivia","Ava","Isabella","Sophia","Mia","Charlotte","Amelia","Harper","Evelyn",
    "Fatima","Aisha","Layla","Zahra","Noor","Hana","Yara","Lina","Maya","Inaya","Priya","Ananya",
    "Riya","Neha","Shreya","Pooja","Kavita","Marie","Sophie","Camille","Julie","Claire","Isabelle",
    "Maria","Carmen","Ana","Isabel","Rosa","Marta","Laura","Aiko","Yoshiko","Keiko","Sachiko"]
SURNAMES = ["Smith","Johnson","Williams","Brown","Jones","Garcia","Miller","Davis","Rodriguez",
    "Martinez","Hernandez","Lopez","Gonzalez","Wilson","Anderson","Thomas","Taylor","Moore",
    "Jackson","Martin","Lee","Perez","Thompson","White","Harris","Sanchez","Clark","Ramirez",
    "Lewis","Robinson","Kim","Park","Choi","Jung","Kang","Cho","Yoon","Chang","Lim",
    "Wang","Li","Zhang","Chen","Liu","Yang","Huang","Wu","Zhou","Xu","Patel","Kumar",
    "Singh","Shah","Sharma","Gupta","Mehta","Joshi","Verma","Rao","Cohen","Levy","Friedman",
    "Rossi","Ferrari","Bianchi","Romano","Colombo","Ricci","Marino","Greco","Bruno",
    "Suzuki","Takahashi","Tanaka","Watanabe","Ito","Yamamoto","Nakamura","Sato","Yoshida","Yamada"]
LANGUAGES = ["English","Mandarin","Hindi","Spanish","French","Arabic","Bengali","Russian","Portuguese",
    "Urdu","German","Japanese","Swahili","Tamil","Telugu","Turkish","Italian","Vietnamese","Korean",
    "Polish","Dutch","Thai","Greek","Czech","Swedish","Hungarian","Romanian","Ukrainian","Hebrew",
    "Persian","Malay","Filipino","Burmese","Serbian","Croatian","Bulgarian","Danish","Finnish",
    "Norwegian","Slovak","Lithuanian","Latvian","Slovenian","Estonian","Georgian","Armenian",
    "Mongolian","Nepali","Sinhala","Khmer","Lao"]
ANIMALS = ["Lion","Tiger","Elephant","Giraffe","Zebra","Rhinoceros","Hippopotamus","Leopard",
    "Cheetah","Gorilla","Chimpanzee","Orangutan","Panda","Koala","Kangaroo","Crocodile",
    "Python","Eagle","Hawk","Falcon","Parrot","Peacock","Penguin","Dolphin","Whale","Shark",
    "Octopus","Wolf","Fox","Bear","Deer","Moose","Bison","Antelope","Gazelle","Rabbit",
    "Squirrel","Beaver","Otter","Hedgehog","Badger","Raccoon","Ostrich","Flamingo","Swan",
    "Turtle","Tortoise","Lizard","Gecko","Iguana","Chameleon","Frog","Toad"]
PLANTS = ["Oak","Maple","Pine","Spruce","Cedar","Birch","Willow","Rose","Lily","Tulip",
    "Orchid","Sunflower","Daisy","Lavender","Jasmine","Lotus","Cherry","Wheat","Rice",
    "Corn","Barley","Oats","Sugarcane","Cotton","Apple","Orange","Banana","Grape",
    "Strawberry","Mango","Tomato","Potato","Carrot","Onion","Garlic","Coffee","Tea",
    "Cocoa","Vanilla","Cinnamon","Ginger","Turmeric","Aloe","Fern","Cactus","Bamboo","Palm"]
SPORTS = ["Soccer","Basketball","Tennis","Cricket","Baseball","Rugby","Golf","Swimming",
    "Volleyball","Badminton","Boxing","Wrestling","Fencing","Archery","Cycling","Rowing",
    "Gymnastics","Judo","Taekwondo","Karate","Skiing","Ice Hockey","Handball","Hockey",
    "Water Polo","Diving","Triathlon","Curling","Lacrosse","Squash","Netball","Polo"]

# 100 topic generators
topics = [
    ("famous_battle", lambda: (random.choice(["Battle of","Siege of","Invasion of","Campaign of"])+" "+random.choice(CITIES),
        random.choice(["World War II","WWI","Napoleonic","Civil War","Ancient","Medieval","Revolution"]),
        random.randint(-500,1945), random.choice(COUNTRIES), random.choice(["Decisive","Pyrrhic","Stalemate","Surprise"]))),
    ("major_war_conflict", lambda: (random.choice(["World War","Civil War","Revolution","War of Independence",
        "War of the Roses","Hundred Years War","Crusade","Conquest"]),
        random.randint(1000,2020), random.randint(2,50), random.choice(COUNTRIES),
        random.choice(["Global","Regional","Civil","Colonial"]))),
    ("world_flag_detail", lambda: (random.choice(COUNTRIES),
        random.choice(["Red,White,Blue","Green,White,Red","Blue,Yellow,Red","Black,Red,Gold",
            "Red,White","Green,Yellow,Red","Blue,White","Red,Yellow,Green"]),
        random.choice(["Horizontal","Vertical","Diagonal","Saltire","Tricolour"]),
        str(random.randint(1800,2000)))),
    ("world_capital_city", lambda: (random.choice(CITIES), random.choice(COUNTRIES),
        random.randint(100000,20000000), random.randint(100,5000),
        random.choice(["Founded","Ancient","Colonial","Modern"]))),
    ("world_island_detail", lambda: (random.choice(["Madagascar","Greenland","Borneo","Sumatra","Honshu",
        "Java","Sri Lanka","Tasmania","Iceland","Ireland","Sicily","Barbados","Fiji","Bali","Cuba",
        "Jamaica","Taiwan","Luzon","Mindanao","Crete","Maui","Oahu","Sardinia","Cyprus"]),
        random.randint(100,2000000), random.choice(COUNTRIES),
        random.choice(["Pacific","Atlantic","Indian","Mediterranean","Caribbean"]))),
    ("world_desert_detail", lambda: (random.choice(["Sahara","Gobi","Kalahari","Atacama","Mojave","Namib",
        "Sonoran","Arabian","Thar","Patagonian","Great Victoria","Taklamakan","Kyzylkum","Karakum","Simpson",
        "Chihuahuan","Negev","Dasht-e Lut","Dasht-e Kavir","Ryn"]),
        random.randint(10000,9000000), random.choice(["Africa","Asia","South America","North America","Australia"]),
        random.choice(["Hot","Cold","Coastal","Semi-arid","Polar"]))),
    ("world_forest_detail", lambda: (random.choice(["Amazon","Congo","Taiga","Black Forest","Sherwood",
        "Daintree","Borneo","Sundarbans","Tongass","Bialowieza","Sinharaja","Monteverde","Amazonia",
        "Yakushima","Hoh","Redwood","Sequoia","Olympic","Pine Barrens","New Forest"]),
        random.randint(100,5500000), random.choice(COUNTRIES),
        random.choice(["Tropical","Temperate","Boreal","Rainforest","Deciduous","Coniferous"]))),
    ("national_anthem_detail", lambda: (random.choice(COUNTRIES),
        random.choice(["March","Hymn","Song","Anthem","Ode"]),
        str(random.randint(1700,2000)),
        random.choice(NAMES)+" "+random.choice(SURNAMES))),
    ("world_landmark_data", lambda: (random.choice(["Eiffel Tower","Colosseum","Taj Mahal","Statue of Liberty",
        "Great Wall","Machu Picchu","Christ the Redeemer","Pyramids of Giza","Stonehenge",
        "Petra","Angkor Wat","Golden Gate","Brooklyn Bridge","Sydney Opera House",
        "Leaning Tower of Pisa","Burj Khalifa","Mount Rushmore","Niagara Falls","Grand Canyon",
        "Table Mountain","Acropolis","Parthenon","Notre Dame","Big Ben"]),
        random.choice(CITIES), random.choice(COUNTRIES), str(random.randint(-2500,2000)),
        random.choice(["Ancient","Medieval","Modern","Natural"]))),
    ("world_heritage_extra", lambda: (random.choice(["Great Pyramids","Great Barrier Reef","Taj Mahal",
        "Machu Picchu","Colosseum","Angkor Wat","Acropolis","Stonehenge","Versailles","Yellowstone",
        "Galapagos","Serengeti","Great Wall","Petra","Easter Island","Chichen Itza","Niagara",
        "Grand Canyon","Yellowstone","Banff","Fiordland","Galapagos","Alhambra","Hagia Sophia"]),
        random.choice(COUNTRIES), str(random.randint(1978,2024)),
        random.choice(["Cultural","Natural","Mixed","World Heritage"]))),
    ("nobel_category_detail", lambda: (random.choice(["Physics","Chemistry","Medicine","Literature","Peace","Economics"]),
        random.choice(NAMES+NAMES_F)+" "+random.choice(SURNAMES), str(random.randint(1901,2024)),
        random.choice(["Discovery","Theory","Innovation","Humanitarian"]))),
    ("world_river_detail", lambda: (random.choice(["Nile","Amazon","Yangtze","Mississippi","Yenisei","Yellow River",
        "Ob","Parana","Irtysh","Zaire","Mekong","Niger","Volga","Brahmaputra","Indus","Yukon","Danube","Ganges",
        "Murray","Tigris","Euphrates","Orinoco","Zambezi","Godavari","Colorado","Rio Grande","Rhine","Po","Seine",
        "Thames","Tagus","Elbe","Vistula","Loire","Douro","Ebro","Rhone","Dnieper","Don","Ural"]),
        random.randint(500,7000), random.choice(COUNTRIES),
        random.choice(["Alpine","Tropical","Seasonal","Perennial"]))),
    ("mountain_range_data", lambda: (random.choice(["Himalayas","Andes","Alps","Rocky Mountains","Urals",
        "Atlas Mountains","Caucasus","Altai","Tian Shan","Karakoram","Hindu Kush","Pamir",
        "Appalachians","Sierra Nevada","Pyrenees","Carpathians","Drakensberg","Great Dividing Range",
        "Transantarctic","Zagros","Elburz","Ethiopian Highlands","Annamese Cordillera","Scandinavian"]),
        random.randint(1000,9000), random.randint(100,3000), random.choice(COUNTRIES),
        random.choice(["Formed","Active","Eroding","Volcanic"]))),
    ("famous_beach_data", lambda: (random.choice(["Copacabana","Bondi","Waikiki","Miami Beach","Ipanema",
        "Cannes","Cancun","Phuket","Bora Bora","Maldives","Santorini","Mykonos","Zanzibar","Whitehaven",
        "Navagio","Seven Mile","Kailua","Lanikai","Grace Bay","Varadero","Playa del Carmen","Kuta",
        "Patong","Nha Trang","Bali"]),
        random.choice(COUNTRIES), random.choice(["Atlantic","Pacific","Indian","Mediterranean","Caribbean"]),
        random.choice(["White sand","Golden sand","Black sand","Pink sand","Coral"]))),
    ("ski_resort_data", lambda: (random.choice(["Aspen","Vail","Whistler","Chamonix","St. Moritz","Zermatt",
        "Courchevel","Val d'Isere","Kitzbuhel","St. Anton","Jackson Hole","Park City","Lake Tahoe",
        "Banff","Niseko","Hakuba","Andermatt","Verbier","Crans-Montana","Lech","Ischgl","Saalbach",
        "Sölden","Mayrhofen","Garmisch"]),
        random.choice(["USA","France","Switzerland","Austria","Italy","Canada","Japan","Germany"]),
        random.randint(500,4000), random.randint(10,250))),
    ("golf_course_data", lambda: (random.choice(["Augusta National","St. Andrews","Pebble Beach","Cypress Point",
        "Pine Valley","Merion","Oakmont","Winged Foot","Shinnecock","Royal Portrush","Carnoustie",
        "Royal Birkdale","Muirfield","Turnberry","Sawgrass","Kiawah Island","Whistling Straits",
        "Hazeltine","Bethpage Black","Torrey Pines","Riviera","Wentworth","Gleneagles","Valderrama",
        "Royal Melbourne"]),
        random.choice(COUNTRIES), str(random.randint(1890,2000)),
        random.choice(["Links","Parkland","Desert","Mountain","Coastal"]))),
    ("motorsport_track_data", lambda: (random.choice(["Monza","Silverstone","Spa-Francorchamps","Nürburgring",
        "Monaco","Suzuka","Interlagos","Imola","Zandvoort","Yas Marina","Albert Park","Sepang",
        "Shanghai","Circuit of the Americas","Red Bull Ring","Hungaroring","Bahrain","Jeddah",
        "Losail","Baku","Marina Bay","Hockenheim","Paul Ricard","Catalunya"]),
        random.choice(["Italy","UK","Belgium","Germany","Monaco","Japan","Brazil","Australia",
            "USA","Austria","Hungary","Bahrain","Saudi Arabia","Qatar","Azerbaijan","Singapore",
            "Spain","France","UAE"]), random.randint(1950,2020), random.randint(3,7))),
    ("famous_horse_data", lambda: (random.choice(["Secretariat","Man o' War","Seabiscuit","Phar Lap",
        "Frankel","American Pharoah","Justify","California Chrome","Arrogate","Flightline",
        "Native Dancer","Citation","Count Fleet","Assault","War Admiral","Omaha","Gallant Fox",
        "Sir Barton","Whirlaway","Affirmed","Seattle Slew","Alysheba","Sunday Silence","Makybe Diva"]),
        str(random.randint(1920,2020)), random.choice(COUNTRIES),
        random.choice(["Triple Crown","Derby","Stakes","Handicap"]))),
    ("award_ceremony_data", lambda: (random.choice(["Academy Awards","Grammy Awards","Emmy Awards","Tony Awards",
        "BAFTA Awards","Golden Globes","MTV Awards","Billboard Awards","Brit Awards","People's Choice",
        "American Music Awards","Country Music Awards","BET Awards","Oscar","Razzie Awards",
        "Cannes Film Festival","Venice Film Festival","Berlin Film Festival","Sundance","Toronto Film Festival"]),
        str(random.randint(1929,2020)), random.choice(["USA","UK","France","Italy","Canada"]),
        random.choice(["Film","Music","Television","Theatre","General"]))),
    ("film_festival_detail", lambda: (random.choice(["Cannes","Venice","Berlin","Sundance","Toronto",
        "Tribeca","SXSW","Telluride","Locarno","Karlovy Vary","San Sebastian","Busan",
        "Tokyo","Shanghai","Cairo","Mar del Plata","Moscow","Warsaw","Melbourne","Sydney"]),
        str(random.randint(1932,2000)), random.choice(COUNTRIES),
        random.choice(["A-category","Independent","Specialized","Documentary"]))),
    ("tv_series_detail", lambda: (random.choice(["Breaking Bad","Game of Thrones","Stranger Things",
        "The Crown","The Office","Friends","Seinfeld","The Simpsons","South Park","Rick and Morty",
        "Better Call Saul","Mad Men","The Wire","Sopranos","Lost","Walking Dead","True Detective",
        "Fargo","Westworld","Black Mirror","Dark","Narcos","Peaky Blinders","Sherlock","Downton Abbey"]),
        random.randint(1,12), random.randint(10,250),
        random.choice(["Drama","Comedy","Sci-Fi","Thriller","Fantasy","Crime","Horror"]))),
    ("anime_series_detail", lambda: (random.choice(["Naruto","One Piece","Attack on Titan","Death Note",
        "Fullmetal Alchemist","Dragon Ball Z","My Hero Academia","Demon Slayer","Jujutsu Kaisen",
        "Spirited Away","Princess Mononoke","Howl's Moving Castle","Cowboy Bebop","Neon Genesis",
        "Evangelion","Steins;Gate","Hunter x Hunter","Bleach","One Punch Man","Tokyo Ghoul",
        "Parasyte","Vinland Saga","Mob Psycho","Akira","Ghost in the Shell"]),
        random.choice(["Action","Adventure","Fantasy","Sci-Fi","Slice of Life","Mecha","Horror"]),
        random.randint(1990,2024), random.randint(12,1000))),
    ("video_game_franchise", lambda: (random.choice(["Mario","Zelda","Pokemon","Final Fantasy","Elder Scrolls",
        "Call of Duty","Assassin's Creed","Grand Theft Auto","Minecraft","Fortnite","League of Legends",
        "World of Warcraft","Diablo","Overwatch","Dark Souls","God of War","Spider-Man","Batman",
        "Resident Evil","Metal Gear Solid","Street Fighter","Tekken","Civilization","Sims","FIFA"]),
        random.choice(["Action","RPG","Adventure","Simulation","Sports","Strategy","FPS","Fighting"]),
        random.randint(1980,2020), random.randint(1000000,500000000))),
    ("board_game_detail", lambda: (random.choice(["Chess","Monopoly","Risk","Catan","Carcassonne",
        "Ticket to Ride","Pandemic","Azul","Wingspan","Terraforming Mars","7 Wonders","Gloomhaven",
        "Brass Birmingham","Power Grid","Dominion","Agricola","Twilight Struggle","Terra Mystica",
        "Everdell","Root","Scythe","Spirit Island","Dune Imperium","Ark Nova","Great Western Trail"]),
        random.randint(2,8), random.randint(30,180),
        random.choice(["Strategy","Eurogame","Thematic","Party","Abstract","Cooperative"]))),
    ("card_game_detail", lambda: (random.choice(["Poker","Bridge","Hearts","Spades","Solitaire","Rummy",
        "Crazy Eights","Uno","Magic The Gathering","Yu-Gi-Oh","Pokemon TCG","Hearthstone",
        "Clash Royale","Gwent","Legends of Runeterra","Slay the Spire","Marvel Snap","Go Fish",
        "War","Blackjack","Baccarat","Cribbage","Pinochle","Euchre","Canasta"]),
        random.choice(["Classic","Trading Card","Collectible","Digital","Casino"]),
        random.randint(2,10), random.choice(["Deck-building","Trick-taking","Matching","Strategic"]))),
    ("martial_art_style", lambda: (random.choice(["Karate","Judo","Taekwondo","Kung Fu","Muay Thai",
        "Brazilian Jiu-Jitsu","Boxing","Wrestling","Aikido","Hapkido","Kendo","Capoeira",
        "Krav Maga","Wing Chun","Jeet Kune Do","Tai Chi","Ninjutsu","Sumo","Kickboxing",
        "Savate","Silat","Escrima","Kali","Arnis","Kalaripayattu"]),
        random.choice(["Japan","South Korea","China","Thailand","Brazil","USA","Israel","Philippines",
            "France","India"]), str(random.randint(500,1950)),
        random.choice(["Striking","Grappling","Weapons","Mixed","Internal"]))),
    ("yoga_pose_data", lambda: (random.choice(["Downward Dog","Warrior I","Warrior II","Tree Pose",
        "Mountain Pose","Child's Pose","Cobra Pose","Triangle Pose","Half Moon","Crow Pose",
        "Headstand","Shoulder Stand","Plow Pose","Fish Pose","Lotus Pose","Seated Forward Fold",
        "Bridge Pose","Wheel Pose","Pigeon Pose","Happy Baby","Cat Pose","Cow Pose","Eagle Pose",
        "Dancer Pose","King Pigeon"]),
        random.choice(["Standing","Seated","Supine","Prone","Balance","Inversion","Twist"]),
        random.choice(["Beginner","Intermediate","Advanced","Expert"]),
        random.choice(["Balance","Flexibility","Strength","Relaxation","Energizing"]))),
    ("famous_painting_data", lambda: (random.choice(["Mona Lisa","The Starry Night","The Scream","Guernica",
        "The Persistence of Memory","Girl with a Pearl Earring","The Night Watch","The Birth of Venus",
        "Creation of Adam","The Last Supper","Starry Night Over the Rhone","Water Lilies",
        "Impression Sunrise","American Gothic","Whistler's Mother","The Kiss","The Thinker",
        "Les Demoiselles d'Avignon","Campbell's Soup Cans","No.5 1948"]),
        random.choice(NAMES+NAMES_F)+" "+random.choice(SURNAMES), str(random.randint(1400,1960)),
        random.choice(["Renaissance","Baroque","Impressionist","Modern","Pop Art","Surrealist"]))),
    ("opera_house_detail", lambda: (random.choice(["Sydney Opera House","La Scala","Royal Opera House",
        "Vienna State Opera","Metropolitan Opera","Paris Opera","Bolshoi Theatre","Teatro Colon",
        "San Carlo","La Fenice","Semperoper","Bavarian State Opera","Zurich Opera House",
        "Royal Danish Theatre","Norwegian Opera","Oslo Opera","Copenhagen Opera","Mariinsky Theatre",
        "Grand Theatre Warsaw","Teatro Real","Liceu","Palermo Teatro Massimo","Opera Garnier"]),
        random.choice(COUNTRIES), random.randint(1500,2800),
        str(random.randint(1700,2000)))),
    ("concert_hall_detail", lambda: (random.choice(["Carnegie Hall","Royal Albert Hall","Berlin Philharmonic",
        "Wiener Musikverein","Concertgebouw","Boston Symphony Hall","Salle Pleyel","Barbican Hall",
        "Suntory Hall","Tonhalle Zurich","Gewandhaus","Elbphilharmonie","Musikverein","Sydney Opera Concert",
        "Walt Disney Hall","Davies Symphony Hall","Moscow Conservatory","Tchaikovsky Hall",
        "Koln Philharmonic","Alte Oper","Hercules Hall","Brucknerhaus","Mozarteum","Lucerne Hall"]),
        str(random.randint(1870,2000)), random.randint(1000,3500),
        random.choice(["Symphony","Recital","Multi-purpose","Opera"]))),
    ("music_festival_detail", lambda: (random.choice(["Glastonbury","Coachella","Lollapalooza","Burning Man",
        "Tomorrowland","Roskilde","Woodstock","Montreux Jazz","Newport Jazz","Austin City Limits",
        "Electric Daisy Carnival","Ultra Music Festival","Sziget","Reading and Leeds","Primavera Sound",
        "Rock in Rio","Hellfest","Wacken Open Air","Download Festival","Pinkpop","Lowlands",
        "Exit Festival","Sonic Temple","Bonnaroo","Governors Ball"]),
        random.choice(["Rock","Electronic","Jazz","Metal","Pop","Hip Hop","Mixed"]),
        random.choice(["USA","UK","Belgium","Denmark","Netherlands","Portugal","Brazil","Germany","Serbia"]),
        str(random.randint(1960,2010)))),
    ("famous_poem_data", lambda: (random.choice(["The Raven","The Road Not Taken","If","The Waste Land",
        "Ode to a Nightingale","Daffodils","Kubla Khan","Sonnet 18","The Love Song of J. Alfred Prufrock",
        "Do Not Go Gentle","Stopping by Woods","The Second Coming","Invictus","Still I Rise",
        "Howl","Annabel Lee","Jabberwocky","Charge of the Light Brigade","Ozymandias","The Tyger"]),
        random.choice(NAMES+NAMES_F)+" "+random.choice(SURNAMES), str(random.randint(1600,1950)),
        random.choice(["Sonnet","Lyric","Narrative","Free Verse","Epic","Ballad"]))),
    ("shakespeare_play_data", lambda: (random.choice(["Hamlet","Macbeth","Romeo and Juliet","Othello",
        "King Lear","The Tempest","A Midsummer Night's Dream","Much Ado About Nothing","Twelfth Night",
        "Julius Caesar","Richard III","Henry V","The Merchant of Venice","As You Like It",
        "The Taming of the Shrew","The Winter's Tale","Measure for Measure","Antony and Cleopatra",
        "Coriolanus","Love's Labour's Lost","Comedy of Errors","Henry IV Part 1","Henry IV Part 2",
        "Richard II","All's Well That Ends Well"]),
        random.choice(["Tragedy","Comedy","History","Romance","Problem Play"]),
        str(random.randint(1590,1612)), random.choice(["Elizabethan","Jacobean","Renaissance"]))),
    ("mythological_creature_data", lambda: (random.choice(["Dragon","Phoenix","Griffin","Unicorn","Centaur",
        "Minotaur","Pegasus","Chimera","Basilisk","Hydra","Cerberus","Cyclops","Medusa",
        "Sphinx","Harpy","Gorgon","Satyr","Pixie","Fairy","Gnome","Troll","Giant",
        "Elf","Dwarf","Valkyrie","Mermaid","Kraken","Leviathan","Behemoth","Thunderbird",
        "Wendigo","Banshee","Leprechaun","Kitsune","Tanuki","Tengu","Yeti","Sasquatch",
        "Chupacabra","Loch Ness Monster","Mothman","Jackalope"]),
        random.choice(["European","Greek","Norse","Japanese","African","Native American","Celtic"]),
        random.choice(["Legendary","Mythical","Folklore","Cryptid"]),
        random.choice(["Air","Earth","Water","Fire","Forest","Mountain"]))),
    ("cryptid_data", lambda: (random.choice(["Bigfoot","Yeti","Loch Ness Monster","Chupacabra","Mothman",
        "Jersey Devil","Flatwoods Monster","Dover Demon","Hopkinsville Goblins","Skunk Ape",
        "Fouke Monster","Momo the Monster","Ozark Howler","Wendigo","Thunderbird","Skinwalker",
        "Goatman","Loveland Frog","Mongolian Death Worm","El Chupacabra","Beast of Bray Road",
        "Bunyip","Drop Bear","Yowie","Mapinguari"]),
        random.choice(["USA","Canada","UK","Mexico","Puerto Rico","Russia","Australia","Brazil",
            "India","Nepal","Mongolia","Argentina"]),
        random.choice(["Humanoid","Reptilian","Canine","Avian","Ungulate"]),
        random.choice(["Witnesses","Hoax","Unconfirmed","Legend"]))),
    ("ghost_town_data", lambda: (random.choice(["Pripyat","Centralia","Bodie","Kolmanskop","Craco",
        "Oradour-sur-Glane","Hashima Island","Pyramiden","Kayakoy","San Zhi","Gunkanjima","Varosha",
        "Belchite","Humberstone","Calico","Rhyolite","St. Elmo","Terlingua","Crystal Mill","Garnet",
        "Kennaook","Silvertown","Goldfield","Ruby","Arizona"]),
        random.choice(COUNTRIES), str(random.randint(1800,1980)),
        random.choice(["Mining","Nuclear","Economic","War","Natural Disaster"]))),
    ("famous_ship_data", lambda: (random.choice(["Titanic","Bismarck","USS Missouri","HMS Victory",
        "Mayflower","Endurance","Beagle","Kon-Tiki","Queen Mary","Lusitania","Andrea Doria",
        "Mary Rose","Vasa","Golden Hind","USS Constitution","HMS Beagle","HMS Bounty",
        "Charles W Morgan","Cutty Sark","Flying Cloud","Great Eastern","SS Normandie",
        "SS United States","RMS Queen Elizabeth","USS Enterprise"]),
        random.choice(["UK","USA","Germany","Spain","Sweden","Norway"]),
        str(random.randint(1500,1960)), random.choice(["Sank","Preserved","Museum","Active"]))),
    ("famous_train_data", lambda: (random.choice(["Orient Express","Trans-Siberian","Flying Scotsman",
        "Shinkansen","TGV","Eurostar","Golden Arrow","Orient Express","Belmond Andean Explorer",
        "Maharajas Express","Royal Scotsman","Blue Train","Ghan","Rocky Mountaineer",
        "Copper Canyon","Venice Simplon","Palace on Wheels","Golden Eagle","Seven Stars",
        "Al Andalus","Rovos Rail","Royal Canadian","Eastern Express","Jungle Train","Death Railway"]),
        random.choice(["Steam","Diesel","Electric","Maglev","High-speed"]),
        random.choice(COUNTRIES), random.randint(1880,2020))),
    ("famous_car_data", lambda: (random.choice(["Ford Model T","Volkswagen Beetle","Toyota Corolla",
        "Honda Civic","Ford Mustang","Chevrolet Corvette","Porsche 911","Ferrari 250 GTO",
        "Lamborghini Miura","Jaguar E-Type","Aston Martin DB5","Mini Cooper","Fiat 500",
        "Land Rover Series I","Jeep Willys","Mercedes 300SL","BMW 2002","Mazda MX-5",
        "Subaru Impreza","Mitsubishi Lancer EVO","Nissan GT-R","Toyota Supra","Honda NSX",
        "Datsun 240Z","Alfa Romeo Giulietta"]),
        random.choice(["USA","Germany","Italy","UK","Japan","France"]),
        str(random.randint(1900,2000)), random.choice(["Sedan","Sports","SUV","Hatchback","Luxury"]))),
    ("famous_aircraft_data", lambda: (random.choice(["Wright Flyer","Boeing 747","Concorde","SR-71 Blackbird",
        "Boeing 737","Airbus A380","Boeing 787","F-16 Falcon","F-22 Raptor","B-52 Stratofortress",
        "C-130 Hercules","P-51 Mustang","Spitfire","Messerschmitt 109","Zero","F-14 Tomcat",
        "F-18 Hornet","Harrier Jump Jet","Lockheed Constellation","DC-3","Boeing 314 Clipper",
        "Hughes H-4 Hercules","Piper Cub","Learjet 35","Gulfstream G650"]),
        random.choice(["Civilian","Military","Experimental","Commercial","Private"]),
        str(random.randint(1903,2000)), random.choice(["USA","UK","Germany","France","Russia"]))),
    ("space_probe_data", lambda: (random.choice(["Voyager 1","Voyager 2","Pioneer 10","Pioneer 11",
        "New Horizons","Cassini","Juno","Galileo","Rosetta","Philae","Hayabusa","Hayabusa2",
        "MESSENGER","Dawn","Stardust","Genesis","Lunar Prospector","Clementine","Chandrayaan",
        "Mars Express","Venus Express","Akatsuki","Parker Solar Probe","Solar Orbiter","BepiColombo"]),
        random.choice(["NASA","ESA","JAXA","ISRO","CNSA","Roscosmos"]),
        str(random.randint(1970,2020)), random.choice(["Flyby","Orbiter","Lander","Sample Return","Rover"]))),
    ("famous_telescope_data", lambda: (random.choice(["Hubble","JWST","Kepler","TESS","Chandra","Spitzer",
        "Herschel","Planck","Gaia","SOHO","STEREO","WMAP","NuSTAR","Fermi","Swift",
        "XMM-Newton","INTEGRAL","Suzaku","ALMA","VLT","Keck","Gemini","Subaru","LBT",
        "Magellan","Arecibo","Green Bank","Very Large Array"]),
        random.choice(["Space","Ground","Radio","Infrared","X-ray","Gamma"]),
        str(random.randint(1960,2022)), random.choice(["NASA","ESA","NSF","JAXA","ESO"]))),
    ("particle_accelerator_data", lambda: (random.choice(["LHC","Tevatron","SLAC","RHIC","LEP","SPS",
        "Tristan","PETRA","HERA","CESR","VEPP","BEPC","KEKB","LHCb","CMS","ATLAS",
        "ALICE","LIGO","Virgo","IceCube","KM3NeT","Super-Kamiokande","SNO","Borexino"]),
        random.choice(["CERN","USA","Japan","Germany","Russia","China","Italy","Canada"]),
        random.randint(1950,2008), random.choice(["Collider","Synchrotron","Fixed Target","Observatory"]))),
    ("nuclear_reactor_data", lambda: (random.choice(["PWR","BWR","CANDU","RBMK","Fast Breeder","VVER",
        "Magnox","HTGR","MSR","Sodium-cooled","Lead-cooled","Gas-cooled","Pressurized Heavy Water",
        "Boiling Water","Advanced Gas-cooled","Light Water","Supercritical","Small Modular","Fusion"]),
        random.choice(["USA","France","Japan","China","Russia","South Korea","India","Canada","UK"]),
        random.randint(1950,2020), random.choice(["Generation II","Generation III","Generation IV","SMR","Fusion"]))),
    ("dam_reservoir_data", lambda: (random.choice(["Hoover Dam","Three Gorges Dam","Itaipu Dam","Aswan Dam",
        "Grand Coulee Dam","Guri Dam","Tarbela Dam","Sayano-Shushenskaya","Krasnoyarsk Dam",
        "Robert-Bourassa Dam","Churchill Falls","Bakun Dam","Karun Dam","Mica Dam","WAC Bennett Dam",
        "Daniel-Johnson Dam","Gordon Dam","Revelstoke Dam","Palmiet Pumped Storage","Inguri Dam"]),
        random.randint(100,40000), random.randint(1000,22000), random.choice(COUNTRIES),
        random.choice(["Hydroelectric","Irrigation","Flood Control","Multi-purpose"]))),
    ("canal_waterway_data", lambda: (random.choice(["Panama Canal","Suez Canal","Erie Canal","Welland Canal",
        "Kiel Canal","Corinth Canal","Panama Canal","Suez Canal","Houston Ship Channel",
        "Manchester Ship Canal","Grand Canal","Albert Canal","Mittellandkanal","Volga-Don Canal",
        "White Sea-Baltic Canal","Moscow Canal","Kiel Canal","Caledonian Canal","Gota Canal",
        "North Sea Canal","Brussels-Charleroi","Saint Lawrence Seaway"]),
        random.randint(5,1800), random.choice(COUNTRIES),
        random.choice(["Sea-level","Lock","Summit","Ship Canal"]))),
    ("tunnel_engineering_data", lambda: (random.choice(["Channel Tunnel","Gotthard Base Tunnel","Seikan Tunnel",
        "Channel Tunnel","L%C3%A6rdal Tunnel","Zhongnanshan Tunnel","Simplon Tunnel","Eurotunnel",
        "St. Gotthard Tunnel","Arlberg Tunnel","Fréjus Tunnel","Mont Blanc Tunnel","Brenner Tunnel",
        "Marmaray Tunnel","Tokyo Bay Aqua-Line","Boston Big Dig","Smart Tunnel","Queensway Tunnel",
        "Mersey Tunnel","Sidney Lanier Bridge","Hålogaland Bridge","Ryfast Tunnel"]),
        random.randint(1,57), random.choice(COUNTRIES),
        random.choice(["Rail","Road","Rail+Road","Subsea","Mountain","Urban"]))),
    ("railway_station_data", lambda: (random.choice(["Grand Central Terminal","St. Pancras","Gare du Nord",
        "Berlin Hauptbahnhof","Madrid Atocha","Roma Termini","Tokyo Station","Shinjuku Station",
        "Central Station Amsterdam","Wien Hauptbahnhof","Zürich Hauptbahnhof","Moscow Kazansky",
        "St Petersburg Moskovsky","Beijing South","Shanghai Hongqiao","London Paddington",
        "Paris Gare de Lyon","Milan Centrale","Munich Hauptbahnhof","Hamburg Hauptbahnhof",
        "Brussels Midi","Oslo Central","Stockholm Central","Copenhagen Central","Helsinki Central"]),
        random.choice(CITIES), random.randint(1850,2000),
        random.choice(["Terminal","Through","Underground","Heritage","Modern"]))),
    ("subway_system_data", lambda: (random.choice(["London Underground","New York Subway","Tokyo Metro",
        "Paris Metro","Moscow Metro","Beijing Subway","Shanghai Metro","Seoul Subway",
        "Madrid Metro","Berlin U-Bahn","Hong Kong MTR","Singapore MRT","Delhi Metro",
        "Sao Paulo Metro","Mexico City Metro","Osaka Metro","Cairo Metro","Istanbul Metro",
        "Sydney Metro","Toronto Subway","Buenos Aires Subte","Stockholm Tunnelbana","Oslo T-bane",
        "Helsinki Metro","Prague Metro"]),
        random.choice(CITIES+["London","Paris","Moscow","Berlin","Madrid","Seoul"]),
        str(random.randint(1863,2010)), random.randint(10,300))),
    ("airport_international_data", lambda: (random.choice(["Heathrow","JFK","Narita","Charles de Gaulle",
        "Dubai International","Changi","Hong Kong","LAX","O'Hare","Haneda","Incheon",
        "Schiphol","Frankfurt","Bangkok Suvarnabhumi","Siem Reap","Istanbul Airport",
        "Doha Hamad","Sydney Kingsford","Melbourne Tullamarine","Barcelona El Prat",
        "Munich","Zurich","Vienna","Milan Malpensa","Copenhagen Kastrup"]),
        random.choice(CITIES), random.randint(1900,2020), random.randint(5000000,100000000))),
    ("famous_hotel_data", lambda: (random.choice(["Burj Al Arab","Ritz Paris","Savoy Hotel","Waldorf Astoria",
        "Marina Bay Sands","Raffles Singapore","The Plaza","Hotel de Paris","Peninsula Hong Kong",
        "Mandarin Oriental","Shangri-La","Four Seasons George V","Grand Budapest Hotel",
        "Bellagio","Venetian","Caesars Palace","MGM Grand","Emirates Palace","Atlantis The Palm",
        "Burj al Arab","Jumeirah Beach","InterContinental","Hilton","Marriott","Ritz-Carlton"]),
        random.choice(CITIES), str(random.randint(1880,2010)),
        random.choice(["Luxury","Boutique","Resort","Business","Heritage","Casino"]))),
    ("casino_landmark_data", lambda: (random.choice(["Bellagio","Caesars Palace","MGM Grand","Venetian",
        "Wynn Las Vegas","Encore","Aria","Cosmopolitan","Mandalay Bay","Luxor","Excalibur",
        "Paris Las Vegas","New York-New York","Monte Carlo","Casino de Monte-Carlo",
        "Marina Bay Sands","Resorts World Sentosa","Crown Melbourne","Casino Lisboa",
        "Casino Royale","Foxwoods","Mohegan Sun","Sun City Casino","Casino Baden-Baden",
        "Casino de Deauville"]),
        random.choice(["Las Vegas","Macau","Monaco","Singapore","Australia","USA","South Africa","Germany","France"]),
        str(random.randint(1850,2010)), random.choice(["Resort","Standalone","Restricted","Boutique"]))),
    ("shopping_mall_detail", lambda: (random.choice(["Mall of America","West Edmonton Mall","Dubai Mall",
        "SM Mall of Asia","Istanbul Cevahir","Mega Mall","Siam Paragon","CentralWorld",
        "Berjaya Times Square","Golden Resources","South China Mall","Moscow GUM",
        "Galleria Vittorio","Harrods","Selfridges","Galeries Lafayette","KaDeWe",
        "Harvey Nichols","Isetan","Mitsukoshi","Takashimaya","Lotte World Mall",
        "Star Mall","Plaza Indonesia","Grand Indonesia"]),
        random.choice(CITIES), random.randint(1990,2015), random.randint(100,600))),
    ("theme_park_data", lambda: (random.choice(["Disneyland","Magic Kingdom","Epcot","Universal Studios",
        "DisneySea","Everland","Lotte World","Alton Towers","Gardaland","Europa Park",
        "Tivoli Gardens","Legoland","Six Flags Magic Mountain","Cedar Point","Kings Island",
        "Busch Gardens","SeaWorld","Disneyland Paris","Tokyo Disneyland","Hong Kong Disneyland",
        "Disney California Adventure","Islands of Adventure","Ferrari World","Motiongate"]),
        random.choice(["USA","Japan","South Korea","UK","Italy","Germany","Denmark","Spain","France","UAE"]),
        random.randint(1955,2020), random.randint(1000000,20000000))),
    ("sports_stadium_data", lambda: (random.choice(["Wembley Stadium","Camp Nou","Old Trafford","Santiago Bernabeu",
        "Signal Iduna Park","Allianz Arena","San Siro","Stade de France","Luzhniki Stadium",
        "Maracana","Estadio Monumental","Azteca Stadium","Yankee Stadium","Fenway Park",
        "Wrigley Field","Dodger Stadium","Madison Square Garden","Staples Center",
        "O2 Arena","Rogers Centre","Sydney Cricket Ground","MCG","Eden Gardens","Lord's","The Oval"]),
        random.choice(CITIES), random.randint(1890,2012),
        random.choice(["Football","Baseball","Basketball","Multi-purpose","Cricket"]))),
    ("olympic_games_detail", lambda: (random.choice(["Athens 1896","London 1908","Berlin 1936","Helsinki 1952",
        "Rome 1960","Tokyo 1964","Mexico City 1968","Munich 1972","Moscow 1980","Los Angeles 1984",
        "Seoul 1988","Barcelona 1992","Atlanta 1996","Sydney 2000","Athens 2004","Beijing 2008",
        "London 2012","Rio 2016","Tokyo 2020","Paris 2024"]),
        random.randint(1900,2024), random.randint(10,200),
        random.choice(["Summer","Winter","Youth","Paralympic"]))),
    ("fifa_world_cup_data", lambda: (random.choice(["Uruguay 1930","Italy 1934","France 1938","Brazil 1950",
        "Switzerland 1954","Sweden 1958","Chile 1962","England 1966","Mexico 1970","West Germany 1974",
        "Argentina 1978","Spain 1982","Mexico 1986","Italy 1990","USA 1994","France 1998",
        "South Korea/Japan 2002","Germany 2006","South Africa 2010","Brazil 2014","Russia 2018","Qatar 2022"]),
        random.choice(COUNTRIES), random.randint(50000,120000), random.choice(["Group+KO","KO"]))),
    ("cricket_world_cup_data", lambda: (random.choice(["England 1975","England 1979","England 1983",
        "India 1987","Australia 1992","India 1996","England 1999","South Africa 2003",
        "West Indies 2007","India 2011","Australia 2015","England 2019","India 2023"]),
        random.choice(COUNTRIES+["West Indies"]), random.randint(10000,80000),
        random.choice(["ODI","T20","Test"]))),
    ("rugby_world_cup_data", lambda: (random.choice(["New Zealand 1987","England 1991","South Africa 1995",
        "Wales 1999","Australia 2003","France 2007","New Zealand 2011","England 2015",
        "Japan 2019","France 2023"]),
        random.choice(["New Zealand","England","South Africa","Wales","Australia","France","Japan"]),
        str(random.randint(1987,2023)), random.randint(50000,100000))),
    ("tour_de_france_data", lambda: (random.choice(["1903","1910","1920","1930","1940","1950","1960","1970",
        "1980","1990","2000","2010","2020"]),
        random.choice(NAMES+NAMES_F)+" "+random.choice(SURNAMES),
        random.choice(["France","Belgium","Italy","Spain","USA","UK","Germany","Netherlands"]),
        random.randint(2000,4000))),
    ("us_open_winner_data", lambda: (random.choice(["Men's Singles","Women's Singles","Men's Doubles",
        "Women's Doubles","Mixed Doubles"]),
        random.choice(NAMES+NAMES_F)+" "+random.choice(SURNAMES),
        random.choice(["USA","UK","Australia","Spain","Switzerland","Serbia","Japan","Czech Republic"]),
        str(random.randint(1970,2024)))),
    ("wimbledon_champion_data", lambda: (random.choice(["Gentlemen's Singles","Ladies' Singles",
        "Gentlemen's Doubles","Ladies' Doubles","Mixed Doubles"]),
        random.choice(NAMES+NAMES_F)+" "+random.choice(SURNAMES),
        random.choice(["UK","USA","Australia","Spain","Switzerland","Serbia","Germany","Czech Republic"]),
        str(random.randint(1968,2024)))),
    ("super_bowl_winner_data", lambda: (random.choice(["I","V","X","XX","XXX","XL","L","LIV","LV","LVI","LVII","LVIII"]),
        random.choice(["New England","Kansas City","San Francisco","Dallas","Pittsburgh","Green Bay",
            "New York Giants","Denver","Seattle","Baltimore","Philadelphia","LA Rams",
            "Tampa Bay","Washington","Miami","Las Vegas","Chicago","Indianapolis"]),
        random.randint(1967,2024), random.choice(["AFC","NFC"]))),
    ("nba_champion_data", lambda: (random.choice(["1947","1950","1960","1970","1980","1990","2000",
        "2010","2020","2024"]),
        random.choice(["Boston Celtics","LA Lakers","Chicago Bulls","Golden State Warriors",
            "San Antonio Spurs","Miami Heat","Detroit Pistons","Houston Rockets",
            "Philadelphia 76ers","New York Knicks","Milwaukee Bucks","Denver Nuggets",
            "Cleveland Cavaliers","Toronto Raptors","Dallas Mavericks"]),
        random.choice(["Eastern Conference","Western Conference"]),
        random.choice(["Championship","Finals MVP","Dynasty"]))),
    ("world_series_winner_data", lambda: (random.choice(["1903","1910","1920","1930","1940","1950","1960",
        "1970","1980","1990","2000","2010","2024"]),
        random.choice(["New York Yankees","Boston Red Sox","LA Dodgers","St. Louis Cardinals",
            "San Francisco Giants","Oakland A's","Cincinnati Reds","Chicago Cubs",
            "Houston Astros","Atlanta Braves","Pittsburgh Pirates","Detroit Tigers",
            "Baltimore Orioles","Minnesota Twins","Kansas City Royals"]),
        random.choice(["AL","NL"]), random.randint(4,7))),
    ("stanley_cup_winner_data", lambda: (random.choice(["1927","1950","1970","1980","1990","2000","2010",
        "2020","2024"]),
        random.choice(["Montreal Canadiens","Toronto Maple Leafs","Detroit Red Wings","Boston Bruins",
            "Chicago Blackhawks","Edmonton Oilers","Pittsburgh Penguins","LA Kings",
            "Colorado Avalanche","Tampa Bay Lightning","New York Rangers","New Jersey Devils",
            "Anaheim Ducks","Carolina Hurricanes","Vegas Golden Knights"]),
        random.choice(["Original Six","Expansion","Modern"]),
        random.randint(4,7))),
    ("uefa_cl_data", lambda: (random.choice(["1955","1960","1970","1980","1990","2000","2010","2024"]),
        random.choice(["Real Madrid","AC Milan","Liverpool","Bayern Munich","Barcelona","Ajax",
            "Manchester United","Inter Milan","Juventus","Benfica","Nottingham Forest",
            "Porto","Marseille","Chelsea","Manchester City"]),
        str(random.randint(1955,2024)), random.choice(["UEFA","European Cup","Champions League"]))),
    ("pulitzer_winner_data", lambda: (random.choice(["Fiction","Drama","History","Poetry","Biography",
        "Music","Journalism","Photography"]),
        random.choice(NAMES+NAMES_F)+" "+random.choice(SURNAMES),
        str(random.randint(1917,2024)), random.choice(["Book","Article","Play","Composition","Photo"]))),
    ("academy_award_data", lambda: (random.choice(["Best Picture","Best Director","Best Actor","Best Actress",
        "Supporting Actor","Supporting Actress","Best Original Screenplay","Best Cinematography",
        "Best Visual Effects","Best Animated Feature","Best Documentary","Best International Film"]),
        random.choice(["Drama","Comedy","Action","Historical","Animated","Documentary"]),
        str(random.randint(1929,2024)), random.choice(NAMES+NAMES_F)+" "+random.choice(SURNAMES))),
    ("grammy_award_data", lambda: (random.choice(["Album of the Year","Record of the Year","Song of the Year",
        "Best New Artist","Best Pop Album","Best Rock Album","Best R&B Album","Best Rap Album",
        "Best Country Album","Best Jazz Album","Best Classical Album","Best Music Video"]),
        random.choice(["Pop","Rock","R&B","Rap","Country","Jazz","Classical","Latin","Electronic"]),
        str(random.randint(1959,2024)), random.choice(NAMES+NAMES_F)+" "+random.choice(SURNAMES))),
    ("emmy_award_data", lambda: (random.choice(["Outstanding Drama Series","Outstanding Comedy Series",
        "Outstanding Limited Series","Outstanding Lead Actor","Outstanding Lead Actress",
        "Outstanding Supporting Actor","Outstanding Directing","Outstanding Writing",
        "Outstanding Reality Competition","Outstanding Variety Series","Outstanding Documentary",
        "Outstanding Animated Program"]),
        random.choice(["Drama","Comedy","Reality","Variety","Documentary","Animated"]),
        str(random.randint(1949,2024)), random.choice(["Network","Cable","Streaming"]))),
    ("tony_award_data", lambda: (random.choice(["Best Musical","Best Play","Best Revival of a Musical",
        "Best Revival of a Play","Best Actor in a Musical","Best Actress in a Musical",
        "Best Director","Best Choreography","Best Original Score","Best Book of a Musical",
        "Best Orchestrations","Best Scenic Design","Best Costume Design","Best Lighting Design"]),
        random.choice(["Musical","Play","Revival","Special"]),
        str(random.randint(1947,2024)), random.choice(["Broadway","Off-Broadway"]))),
    ("us_president_detail", lambda: (random.choice(["George Washington","John Adams","Thomas Jefferson",
        "James Madison","James Monroe","John Quincy Adams","Andrew Jackson","Martin Van Buren",
        "Abraham Lincoln","Ulysses S. Grant","Theodore Roosevelt","Woodrow Wilson","FDR",
        "Harry Truman","Dwight Eisenhower","JFK","Lyndon B. Johnson","Richard Nixon",
        "Jimmy Carter","Ronald Reagan","George H.W. Bush","Bill Clinton","George W. Bush",
        "Barack Obama","Donald Trump","Joe Biden"]),
        str(random.randint(1732,1960)), str(random.randint(1789,2024)),
        random.choice(["Federalist","Democratic-Republican","Whig","Democrat","Republican"]))),
    ("british_monarch_data", lambda: (random.choice(["William the Conqueror","Henry II","Richard the Lionheart",
        "King John","Henry VIII","Elizabeth I","James I","Charles I","Charles II",
        "William III","Queen Anne","George I","George II","George III","George IV",
        "William IV","Victoria","Edward VII","George V","Edward VIII","George VI","Elizabeth II",
        "Charles III"]),
        random.choice(["Norman","Plantagenet","Tudor","Stuart","Hanover","Windsor"]),
        random.randint(-1066,1950), random.randint(1,64))),
    ("chinese_dynasty_data", lambda: (random.choice(["Xia","Shang","Zhou","Qin","Han","Three Kingdoms",
        "Jin","Northern and Southern","Sui","Tang","Song","Yuan","Ming","Qing"]),
        str(random.randint(-2000,1644)), random.choice(["Xian","Luoyang","Nanjing","Beijing","Kaifeng","Hangzhou"]),
        random.choice(["Unified","Divided","Prosperous","Declining"]))),
    ("roman_emperor_data", lambda: (random.choice(["Augustus","Tiberius","Caligula","Claudius","Nero",
        "Vespasian","Titus","Domitian","Trajan","Hadrian","Antoninus Pius","Marcus Aurelius",
        "Commodus","Diocletian","Constantine","Julian","Justinian","Augustulus"]),
        random.randint(-27,476), random.randint(1,40),
        random.choice(["Julian-Claudian","Flavian","Antonine","Severan","Tetrarchy","Constantinian"]))),
    ("egyptian_pharaoh_detail", lambda: (random.choice(["Narmer","Khufu","Khafre","Menkaure","Hatshepsut",
        "Thutmose III","Akhenaten","Tutankhamun","Ramesses II","Cleopatra","Nefertiti",
        "Djoser","Sneferu","Amenhotep III","Seti I","Pepi II","Senusret III","Ahmose I"]),
        str(random.randint(-3000,-30)),
        random.choice(["Old Kingdom","Middle Kingdom","New Kingdom","Ptolemaic"]),
        random.choice(["Pyramid builder","Expansionist","Reformer","Last pharaoh"]))),
    ("greek_philosopher_data", lambda: (random.choice(["Socrates","Plato","Aristotle","Thales","Pythagoras",
        "Heraclitus","Democritus","Protagoras","Gorgias","Socrates","Xenophon","Epicurus",
        "Zeno of Citium","Plotinus","Pyrrho","Empedocles","Anaxagoras","Anaximander",
        "Anaximenes","Diogenes","Parmenides","Zeno of Elea","Aristippus","Cicero","Seneca"]),
        str(random.randint(-600,200)), random.choice(["Greek","Roman","Hellenistic","Post-Hellenistic"]),
        random.choice(["Presocratic","Classical","Hellenistic","Roman","Stoic","Epicurean","Skeptic","Cynic"]))),
    ("scientific_theory_data", lambda: (random.choice(["Theory of Relativity","Evolution by Natural Selection",
        "Quantum Mechanics","Heliocentrism","Big Bang Theory","Plate Tectonics","Cell Theory",
        "Atomic Theory","Electromagnetism","Germ Theory of Disease","General Relativity",
        "Special Relativity","Thermodynamics","String Theory","Quantum Field Theory",
        "Special Relativity","Particle Physics","Wave-Particle Duality","Uncertainty Principle",
        "Chaos Theory","Game Theory","Information Theory"]),
        random.choice(NAMES+NAMES_F)+" "+random.choice(SURNAMES), str(random.randint(1500,2020)),
        random.choice(["Confirmed","Tested","Hypothesis","Leading","Debated"]))),
    ("mathematical_constant_data", lambda: (random.choice(["Pi","Euler's Number","Golden Ratio",
        "Euler-Mascheroni Constant","Feigenbaum Constant","Twin Prime Constant","Catalan's Constant",
        "Apéry's Constant","Avogadro's Number","Boltzmann Constant","Planck Constant",
        "Speed of Light","Gravitational Constant","Fine Structure Constant","Cosmological Constant",
        "Champernowne Constant","Gauss's Constant","Glaisher-Kinkelin Constant","Graham's Number",
        "Ω","π","e","φ","γ"]),
        str(random.randint(-500,1975)), random.choice(["Transcendental","Irrational","Algebraic","Rational"]),
        random.choice(["Geometry","Analysis","Number Theory","Physics","Combinatorics"]))),
    ("physical_constant_data", lambda: (random.choice(["Speed of Light","Planck Constant","Gravitational Constant",
        "Elementary Charge","Boltzmann Constant","Gas Constant","Avogadro Number","Fine Structure",
        "Rydberg Constant","Bohr Radius","Electron Mass","Proton Mass","Neutron Mass",
        "Muon Mass","Permittivity of Free Space","Permeability of Free Space","Standard Gravity",
        "Atmospheric Pressure","Stefan-Boltzmann Constant","Wien's Displacement Constant",
        "Faraday Constant","Coulomb Constant","Hubble Constant","Solar Mass","Earth Mass"]),
        str(random.randint(1600,2020)), random.choice(["SI","Natural","Atomic","Planck","Astronomical"]),
        random.choice(["Defined","Measured","Derived","Universal"]))),
    ("famous_experiment_data", lambda: (random.choice(["Michelson-Morley Experiment","Double Slit Experiment",
        "Cavendish Experiment","Galileo's Leaning Tower","Newton's Prism Experiment",
        "Rutherford Gold Foil","Miller-Urey Experiment","Pavlov's Dog","Milgram Experiment",
        "Stanford Prison Experiment","Greenhouse Experiment","Mendel's Pea Plants",
        "Joule's Paddle Wheel Experiment","Faraday's Electromagnetic Induction",
        "Roemer's Speed of Light","Foucault's Pendulum","Stern-Gerlach Experiment",
        "Davisson-Germer Experiment","Hafele-Keating Experiment","ATLAS Higgs Discovery"]),
        random.choice(NAMES+NAMES_F)+" "+random.choice(SURNAMES), str(random.randint(1600,2012)),
        random.choice(["Physics","Biology","Psychology","Chemistry","Astronomy"]))),
    ("famous_equation_data", lambda: (random.choice(["E=mc²","F=ma","E=mc^2","E=hv","PV=nRT",
        "Schrödinger Equation","Navier-Stokes Equations","Maxwell's Equations",
        "Einstein Field Equations","Dirac Equation","Wave Equation","Heat Equation",
        "Euler-Lagrange Equation","Boltzmann Equation","Lorentz Transformations",
        "Stephen-Boltzmann Law","Planck's Law","Bragg's Law","Snell's Law","Ohm's Law",
        "Coulomb's Law","Newton's Law of Gravity","Einstein's Photoelectric Effect",
        "Heisenberg Uncertainty"]),
        random.choice(["Physics","Chemistry","Engineering","Mathematics"]),
        str(random.randint(1600,1920)), random.choice(["Classical","Quantum","Relativistic","Thermodynamic"]))),
    ("programming_lang_history", lambda: (random.choice(["Fortran","LISP","COBOL","ALGOL","BASIC","Pascal",
        "C","C++","Java","Python","Ruby","JavaScript","Perl","PHP","Go","Rust",
        "Swift","Kotlin","TypeScript","Scala","Haskell","Erlang","Clojure","Dart","Lua"]),
        str(random.randint(1950,2015)), random.choice(NAMES)+" "+random.choice(SURNAMES),
        random.choice(["Procedural","OOP","Functional","Scripting","Systems","Web"]))),
    ("operating_system_history", lambda: (random.choice(["Unix","Linux","Windows","macOS","FreeBSD",
        "Android","iOS","MS-DOS","Solaris","AIX","HP-UX","IRIX","VMS","OS/2",
        "BeOS","AmigaOS","Atari TOS","ChromeOS","Ubuntu","Fedora","Debian","Arch",
        "Gentoo","Slackware","Red Hat","SUSE","Mint","ReactOS","Haiku","Plan 9"]),
        random.randint(1960,2020), random.choice(["Desktop","Server","Mobile","Embedded","Mainframe"]),
        random.choice(["Open Source","Proprietary","Free","Unix-like","POSIX"]))),
    ("internet_milestone_data", lambda: (random.choice(["ARPANET Created","TCP/IP Protocol","World Wide Web",
        "First Web Browser","Google Founded","Wikipedia Launched","YouTube Founded",
        "Facebook Launched","Twitter Launched","iPhone Released","AWS Cloud Launch",
        "Chrome Released","Instagram Founded","WhatsApp Founded","Snapchat Launched",
        "Zoom Founded","TikTok Launched","First Email Sent","First Website Created",
        "First Dot Com Bubble","First Billion Users","HTML Created","HTTP Protocol"]),
        str(random.randint(1960,2015)), random.choice(NAMES+NAMES_F)+" "+random.choice(SURNAMES),
        random.choice(["Protocol","Platform","Application","Hardware","Service"]))),
    ("social_media_platform", lambda: (random.choice(["Facebook","Twitter/X","Instagram","YouTube","TikTok",
        "Snapchat","WhatsApp","WeChat","Telegram","Discord","Reddit","LinkedIn",
        "Pinterest","Threads","Mastodon","Bluesky","Truth Social","Clubhouse",
        "Signal","Line","Viber","KakaoTalk","QQ","Weibo","VKontakte"]),
        str(random.randint(2000,2020)), random.choice(["USA","China","Russia","Japan","South Korea","Germany"]),
        random.randint(10000000,3000000000))),
    ("famous_company_history", lambda: (random.choice(["Apple","Microsoft","Google","Amazon","Meta","Tesla",
        "IBM","Intel","Coca-Cola","Pepsi","McDonald's","Starbucks","Nike","Adidas",
        "Toyota","Samsung","Sony","Walmart","Costco","Target","Disney","Netflix",
        "Spotify","Uber","Airbnb"]),
        str(random.randint(1880,2010)), random.choice(["USA","Japan","Germany","South Korea","UK","France"]),
        random.choice(["Technology","Retail","Automotive","Food","Entertainment","Finance"]))),
    ("stock_exchange_data", lambda: (random.choice(["NYSE","NASDAQ","London Stock Exchange","Tokyo Exchange",
        "Shanghai Stock Exchange","Hong Kong Exchange","Euronext","Shenzhen Stock Exchange",
        "TMX Group","Deutsche Börse","SIX Swiss Exchange","Australian Securities",
        "Korea Exchange","BSE India","National Stock Exchange India","Singapore Exchange",
        "Taiwan Stock Exchange","Moscow Exchange","Saudi Stock Exchange","B3 Brazil",
        "BME Spanish Exchanges","Johannesburg Stock Exchange","Mexican Exchange","SET Thailand",
        "IDX Indonesia"]),
        random.choice(CITIES), str(random.randint(1600,2000)), random.randint(100,4000))),
    ("world_currency_data", lambda: (random.choice(["USD","EUR","JPY","GBP","AUD","CAD","CHF","CNY","HKD",
        "SGD","SEK","NOK","DKK","NZD","KRW","INR","RUB","BRL","MXN","TRY",
        "ZAR","PLN","THB","IDR","MYR","PHP","EGP","SAR","AED","ILS",
        "CLP","COP","PEN","VND","NGN","BDT","PKR","IQD","KWD","QAR"]),
        random.choice(COUNTRIES+["Eurozone","Hong Kong","Singapore","UAE","Saudi Arabia","Kuwait"]),
        random.choice(["Fiat","Pegged","Digital","Commodity"]),
        random.choice(["Major","Minor","Exotic","Currency Union"]))),
    ("timezone_detail_data", lambda: (random.choice(["UTC-12","UTC-11","UTC-10","UTC-9","UTC-8","UTC-7",
        "UTC-6","UTC-5","UTC-4","UTC-3","UTC-2","UTC-1","UTC+0","UTC+1","UTC+2","UTC+3",
        "UTC+4","UTC+5","UTC+5:30","UTC+6","UTC+7","UTC+8","UTC+9","UTC+10","UTC+11","UTC+12","UTC+13","UTC+14"]),
        random.randint(1,50), random.choice(COUNTRIES+["Hong Kong","Puerto Rico","Greenland","Fiji"]),
        random.choice(["Standard","Daylight","Full","Half-hour","Quarter-hour"]))),
    ("country_calling_code", lambda: (random.choice(["1","7","20","27","30","31","32","33","34","36",
        "39","40","41","43","44","45","46","47","48","49","51","52","53","54","55",
        "56","57","58","60","61","62","63","64","65","66","81","82","84","86","90",
        "91","92","93","94","95","98","212","213","216","218","220","221","222","223",
        "224","225","226","227","228","229","230","231","232","233","234","235","236",
        "237","238","239","240","241","242","243","244","245","246","247","248","249",
        "250","251","252","253","254","255","256","257","258","260","261","262","263",
        "264","265","266","267","268","269","290","291","297","298","299","350","351",
        "352","353","354","355","356","357","358","359","370","371","372","373","374",
        "375","376","377","378","379","380","381","382","383","385","386","387","389",
        "420","421","423","500","501","502","503","504","505","506","507","508","509",
        "590","591","592","593","594","595","596","597","598","599","670","672","673",
        "674","675","676","677","678","679","680","681","682","683","685","686","687",
        "688","689","690","691","692","693","850","852","853","855","856","880","881",
        "886","960","961","962","963","964","965","966","967","968","970","971","972",
        "973","974","975","976","977","992","993","994","995","996","998"]),
        random.choice(COUNTRIES+["Hong Kong","Kosovo","Palestine","Puerto Rico"]),
        random.choice(["+1","+2","+3","+4","+5","+6","+7","+8","+9","+0"]))),
    ("famous_font_data", lambda: (random.choice(["Times New Roman","Arial","Helvetica","Courier New",
        "Verdana","Georgia","Palatino","Garamond","Bodoni","Futura","Frutiger","Gill Sans",
        "Optima","Rockwell","Univers","Comic Sans","Impact","Trebuchet MS","Lucida Grande",
        "Calibri","Cambria","Candara","Segoe UI","Myriad","Minion"]),
        str(random.randint(1470,2000)), random.choice(NAMES+NAMES_F)+" "+random.choice(SURNAMES),
        random.choice(["Serif","Sans-serif","Script","Display","Monospace"]))),
    ("famous_logo_data", lambda: (random.choice(["Apple","Nike Swoosh","McDonald's Arches","Coca-Cola",
        "Google","Starbucks","FedEx","Shell","Playboy Bunny","Adidas Stripes",
        "Puma Cat","Twitter Bird","Apple","Amazon Smile","Target Bullseye",
        "IBM","Chanel","Mercedes Star","BMW Roundel","Audi Rings",
        "Volkswagen","Pepsi Globe","MasterCard","Louis Vuitton","NASA"]),
        random.choice(["Technology","Fashion","Food","Automotive","Retail","Sports"]),
        random.randint(1886,2010), random.choice(["Abstract","Lettermark","Emblem","Mascot","Combination"]))),
    ("famous_photo_data", lambda: (random.choice(["The Afghan Girl","Tank Man","V-J Day in Times Square",
        "Earthrise","The Burning Monk","The Falling Soldier","Migrant Mother","Lunch atop a Skyscraper",
        "The Terror of War","The Steerage","Dali Atomicus","The Horse in Motion",
        "Raising the Flag on Iwo Jima","Behind the Gare Saint-Lazare","The Pond-Moonlight",
        "Moonrise Hernandez","The Tetons and Snake River","The Blue Marble","Pale Blue Dot",
        "The Hindenburg Disaster","Execution of Nguyen Van Lem","Saigon Execution","Famine in Sudan",
        "The Great Wave off Kanagawa","Tank Man"]),
        random.choice(NAMES+NAMES_F)+" "+random.choice(SURNAMES), str(random.randint(1840,2000)),
        random.choice(["Black and White","Color","Documentary","Portrait","Landscape","Street"]))),
    ("famous_quote_detail", lambda: (random.choice(["The only thing we have to fear is fear itself",
        "To be or not to be","I think therefore I am","Ask not what your country can do for you",
        "Thats one small step for man","Be the change you wish to see","The unexamined life is not worth living",
        "Imagination is more important than knowledge","I have a dream","Veni vidi vici",
        "Cogito ergo sum","Carpe diem","Eureka","Et tu Brute","Cest la vie",
        "Knowledge is power","I came I saw I conquered","The die is cast",
        "Brevity is the soul of wit","To thine own self be true"]),
        random.choice(NAMES+NAMES_F)+" "+random.choice(SURNAMES),
        str(random.randint(-500,2020)),
        random.choice(["Philosophy","Politics","Literature","Science","Inspiration"]))),
    ("famous_motto_data", lambda: (random.choice(["E Pluribus Unum","In God We Trust","Liberty Equality Fraternity",
        "God with Us","Unity in Diversity","Strength through Unity","One for All All for One",
        "Forward Together","Justice Peace and Progress","God Save the King","Dieu et mon Droit",
        "Ich Dien","Mare Liberum","Semper Fidelis","Ad Astra","Per Ardua ad Astra",
        "Lex et Libertas","Vigilamus pro Te","A Mari usque ad Mare"]),
        random.choice(COUNTRIES+["USA","UK","France","Canada","EU","NATO"]),
        random.choice(["National","Military","University","City","Organization"]),
        random.choice(["Latin","French","English","German","Other"]))),
    ("famous_insignia_data", lambda: (random.choice(["Eagle","Lion","Crown","Star","Shield","Cross",
        "Fleur-de-lis","Hammer and Sickle","Double-headed Eagle","Rising Sun",
        "Panda","Mongoose","Camel","Leopard","Lily","Rose","Lotus","Tulip",
        "Thistle","Shamrock","Maple Leaf","Oak Leaf","Palm Tree","Phoenix","Dragon"]),
        random.choice(COUNTRIES+["Ancient Rome","Soviet Union","Holy Roman Empire","Byzantine Empire",
            "Ottoman Empire","British Empire","Spanish Empire"]),
        random.choice(["National","Royal","Military","Religious","Organization"]),
        random.choice(["Animal","Plant","Object","Abstract","Mythological"]))),
    ("heraldry_coat_of_arms", lambda: (random.choice(["Azure","Gules","Vert","Sable","Purpure","Tenné",
        "Argent","Or"]),
        random.choice(["Lion Rampant","Eagle Displayed","Cross Patée","Fleur-de-lis","Castle Triple",
            "Crown Imperial","Star and Crescent","Shield Quartered","Tree Eradicated",
            "Ship Under Sail","Dragon Rampant","Griffin Segreant"]),
        random.choice(["Kingdom","Empire","Republic","Duchy","Principality","City","Family"]),
        random.choice(["Europe","Asia","Africa","Americas","Oceania"]))),
    ("flower_national_data", lambda: (random.choice(["Rose","Lotus","Tulip","Cherry Blossom","Lily",
        "Sunflower","Daisy","Lavender","Jasmine","Orchid","Chrysanthemum","Iris",
        "Magnolia","Peony","Daffodil","Thistle","Shamrock","Edelweiss","Plum Blossom",
        "Frangipani","Bougainvillea","Hibiscus","Bird of Paradise","Protea","Wattle"]),
        random.choice(COUNTRIES), random.choice(["National Flower","National Tree","National Plant"]),
        random.choice(["Symbol of Peace","Symbol of Love","Symbol of Purity","Symbol of Beauty"]))),
    ("animal_national_data", lambda: (random.choice(["Eagle","Lion","Tiger","Bald Eagle","Kangaroo",
        "Panda","Unicorn","Dragon","Peacock","Kiwi","Bison","Beaver","Camel",
        "Llama","Condor","Cockade","Leopard","Elephant","Cattle","Horse",
        "Barn Owl","Robin","Wren","Thunderbird","Raven"]),
        random.choice(COUNTRIES), random.choice(["National Animal","National Bird","National Mammal"]),
        random.choice(["Symbol of Freedom","Symbol of Strength","Symbol of Pride","Mythical"]))),
    ("food_national_dish", lambda: (random.choice(["Pizza","Sushi","Tacos","Paella","Pad Thai","Pho",
        "Biryani","Sashimi","Ramen","Curry","Pierogi","Goulash","Falafel","Couscous",
        "Fish and Chips","Hamburger","Hot Dog","Poutine","Borscht","Moussaka",
        "Sauerbraten","Wiener Schnitzel","Baklava","Ceviche","Kimchi"]),
        random.choice(COUNTRIES), random.choice(["Staple","Street Food","Festive","Comfort Food"]),
        random.choice(["Savory","Sweet","Spicy","Sour","Rice-based","Bread-based","Soup"]))),
    ("drink_national_data", lambda: (random.choice(["Coffee","Tea","Mate","Sake","Beer","Wine","Whiskey",
        "Vodka","Tequila","Rum","Gin","Soju","Kombucha","Kefir","Lassi",
        "Smoothie","Milkshake","Lemonade","Iced Tea","Hot Chocolate","Chai",
        "Matcha","Oolong","Earl Grey","Espresso"]),
        random.choice(COUNTRIES), random.choice(["Hot","Cold","Alcoholic","Non-alcoholic","Fermented"]),
        random.choice(["Caffeinated","Herbal","Dairy","Fruit","Grain-based"]))),
    "end"
]

# Now generate the file
random.seed(123)
lines = ['"""Bulk data module 3 for AI.py v3.8.0 — 100 data functions, ~50K lines."""']
lines.append('')

func_count = 0
for entry in topics:
    if entry == "end":
        break
    name, generator = entry
    func_count += 1
    display_name = name.replace('_',' ').title()
    lines.append('def get_{}_data():'.format(name))
    lines.append('    """')
    lines.append('    {} — 500 entries'.format(display_name))
    lines.append('    """')
    lines.append('    return [')
    for i in range(500):
        data = generator()
        parts = []
        for v in data:
            if isinstance(v, str):
                v_escaped = v.replace('"', '\\"').replace('\\', '\\\\').replace('\'', '\\\'')
                # If string contains single quotes, use double quotes
                if "'" in v_escaped:
                    v_escaped = v_escaped.replace("'", "\\'")
                parts.append('"{}"'.format(v_escaped))
            elif isinstance(v, float):
                parts.append(str(round(v, 2)))
            else:
                parts.append(str(v))
        entry_str = '        (' + ', '.join(parts) + '),'
        lines.append(entry_str)
    lines.append('    ]')
    lines.append('')

output = '\n'.join(lines)
with open('data_bulk3.py', 'w', encoding='utf-8') as f:
    f.write(output)

print('Generated data_bulk3.py: {} functions, {} lines, {:,} chars'.format(func_count, len(lines), len(output)))
