import random, math

def random_country():
    countries = [
        ("Afghanistan", "Kabul", "Afghani"), ("Albania", "Tirana", "Lek"), ("Algeria", "Algiers", "Dinar"),
        ("Andorra", "Andorra la Vella", "Euro"), ("Angola", "Luanda", "Kwanza"), ("Antigua and Barbuda", "Saint John's", "Dollar"),
        ("Argentina", "Buenos Aires", "Peso"), ("Armenia", "Yerevan", "Dram"), ("Australia", "Canberra", "Dollar"),
        ("Austria", "Vienna", "Euro"), ("Azerbaijan", "Baku", "Manat"), ("Bahamas", "Nassau", "Dollar"),
        ("Bahrain", "Manama", "Dinar"), ("Bangladesh", "Dhaka", "Taka"), ("Barbados", "Bridgetown", "Dollar"),
        ("Belarus", "Minsk", "Ruble"), ("Belgium", "Brussels", "Euro"), ("Belize", "Belmopan", "Dollar"),
        ("Benin", "Porto-Novo", "Franc"), ("Bhutan", "Thimphu", "Ngultrum"), ("Bolivia", "Sucre", "Boliviano"),
        ("Bosnia and Herzegovina", "Sarajevo", "Marka"), ("Botswana", "Gaborone", "Pula"), ("Brazil", "Brasilia", "Real"),
        ("Brunei", "Bandar Seri Begawan", "Dollar"), ("Bulgaria", "Sofia", "Lev"), ("Burkina Faso", "Ouagadougou", "Franc"),
        ("Burundi", "Gitega", "Franc"), ("Cabo Verde", "Praia", "Escudo"), ("Cambodia", "Phnom Penh", "Riel"),
        ("Cameroon", "Yaounde", "Franc"), ("Canada", "Ottawa", "Dollar"), ("Central African Republic", "Bangui", "Franc"),
        ("Chad", "N'Djamena", "Franc"), ("Chile", "Santiago", "Peso"), ("China", "Beijing", "Yuan"),
        ("Colombia", "Bogota", "Peso"), ("Comoros", "Moroni", "Franc"), ("Congo", "Brazzaville", "Franc"),
        ("Costa Rica", "San Jose", "Colon"), ("Croatia", "Zagreb", "Euro"), ("Cuba", "Havana", "Peso"),
        ("Cyprus", "Nicosia", "Euro"), ("Czech Republic", "Prague", "Koruna"), ("Denmark", "Copenhagen", "Krone"),
        ("Djibouti", "Djibouti", "Franc"), ("Dominica", "Roseau", "Dollar"), ("Dominican Republic", "Santo Domingo", "Peso"),
        ("Ecuador", "Quito", "Dollar"), ("Egypt", "Cairo", "Pound"), ("El Salvador", "San Salvador", "Dollar"),
        ("Equatorial Guinea", "Malabo", "Franc"), ("Eritrea", "Asmara", "Nakfa"), ("Estonia", "Tallinn", "Euro"),
        ("Eswatini", "Mbabane", "Lilangeni"), ("Ethiopia", "Addis Ababa", "Birr"), ("Fiji", "Suva", "Dollar"),
        ("Finland", "Helsinki", "Euro"), ("France", "Paris", "Euro"), ("Gabon", "Libreville", "Franc"),
        ("Gambia", "Banjul", "Dalasi"), ("Georgia", "Tbilisi", "Lari"), ("Germany", "Berlin", "Euro"),
        ("Ghana", "Accra", "Cedi"), ("Greece", "Athens", "Euro"), ("Grenada", "Saint George's", "Dollar"),
        ("Guatemala", "Guatemala City", "Quetzal"), ("Guinea", "Conakry", "Franc"), ("Guinea-Bissau", "Bissau", "Franc"),
        ("Guyana", "Georgetown", "Dollar"), ("Haiti", "Port-au-Prince", "Gourde"), ("Honduras", "Tegucigalpa", "Lempira"),
        ("Hungary", "Budapest", "Forint"), ("Iceland", "Reykjavik", "Krona"), ("India", "New Delhi", "Rupee"),
        ("Indonesia", "Jakarta", "Rupiah"), ("Iran", "Tehran", "Rial"), ("Iraq", "Baghdad", "Dinar"),
        ("Ireland", "Dublin", "Euro"), ("Israel", "Jerusalem", "Shekel"), ("Italy", "Rome", "Euro"),
        ("Jamaica", "Kingston", "Dollar"), ("Japan", "Tokyo", "Yen"), ("Jordan", "Amman", "Dinar"),
        ("Kazakhstan", "Nur-Sultan", "Tenge"), ("Kenya", "Nairobi", "Shilling"), ("Kiribati", "Tarawa", "Dollar"),
        ("Korea North", "Pyongyang", "Won"), ("Korea South", "Seoul", "Won"), ("Kosovo", "Pristina", "Euro"),
        ("Kuwait", "Kuwait City", "Dinar"), ("Kyrgyzstan", "Bishkek", "Som"), ("Laos", "Vientiane", "Kip"),
        ("Latvia", "Riga", "Euro"), ("Lebanon", "Beirut", "Pound"), ("Lesotho", "Maseru", "Loti"),
        ("Liberia", "Monrovia", "Dollar"), ("Libya", "Tripoli", "Dinar"), ("Liechtenstein", "Vaduz", "Franc"),
        ("Lithuania", "Vilnius", "Euro"), ("Luxembourg", "Luxembourg", "Euro"), ("Madagascar", "Antananarivo", "Ariary"),
        ("Malawi", "Lilongwe", "Kwacha"), ("Malaysia", "Kuala Lumpur", "Ringgit"), ("Maldives", "Male", "Rufiyaa"),
        ("Mali", "Bamako", "Franc"), ("Malta", "Valletta", "Euro"), ("Marshall Islands", "Majuro", "Dollar"),
        ("Mauritania", "Nouakchott", "Ouguiya"), ("Mauritius", "Port Louis", "Rupee"), ("Mexico", "Mexico City", "Peso"),
        ("Micronesia", "Palikir", "Dollar"), ("Moldova", "Chisinau", "Leu"), ("Monaco", "Monaco", "Euro"),
        ("Mongolia", "Ulaanbaatar", "Tugrik"), ("Montenegro", "Podgorica", "Euro"), ("Morocco", "Rabat", "Dirham"),
        ("Mozambique", "Maputo", "Metical"), ("Myanmar", "Naypyidaw", "Kyat"), ("Namibia", "Windhoek", "Dollar"),
        ("Nauru", "Yaren", "Dollar"), ("Nepal", "Kathmandu", "Rupee"), ("Netherlands", "Amsterdam", "Euro"),
        ("New Zealand", "Wellington", "Dollar"), ("Nicaragua", "Managua", "Cordoba"), ("Niger", "Niamey", "Franc"),
        ("Nigeria", "Abuja", "Naira"), ("North Macedonia", "Skopje", "Denar"), ("Norway", "Oslo", "Krone"),
        ("Oman", "Muscat", "Rial"), ("Pakistan", "Islamabad", "Rupee"), ("Palau", "Ngerulmud", "Dollar"),
        ("Palestine", "East Jerusalem", "Shekel"), ("Panama", "Panama City", "Balboa"), ("Papua New Guinea", "Port Moresby", "Kina"),
        ("Paraguay", "Asuncion", "Guarani"), ("Peru", "Lima", "Sol"), ("Philippines", "Manila", "Peso"),
        ("Poland", "Warsaw", "Zloty"), ("Portugal", "Lisbon", "Euro"), ("Qatar", "Doha", "Riyal"),
        ("Romania", "Bucharest", "Leu"), ("Russia", "Moscow", "Ruble"), ("Rwanda", "Kigali", "Franc"),
        ("Saint Kitts and Nevis", "Basseterre", "Dollar"), ("Saint Lucia", "Castries", "Dollar"), ("Saint Vincent", "Kingstown", "Dollar"),
        ("Samoa", "Apia", "Tala"), ("San Marino", "San Marino", "Euro"), ("Sao Tome and Principe", "Sao Tome", "Dobra"),
        ("Saudi Arabia", "Riyadh", "Riyal"), ("Senegal", "Dakar", "Franc"), ("Serbia", "Belgrade", "Dinar"),
        ("Seychelles", "Victoria", "Rupee"), ("Sierra Leone", "Freetown", "Leone"), ("Singapore", "Singapore", "Dollar"),
        ("Slovakia", "Bratislava", "Euro"), ("Slovenia", "Ljubljana", "Euro"), ("Solomon Islands", "Honiara", "Dollar"),
        ("Somalia", "Mogadishu", "Shilling"), ("South Africa", "Pretoria", "Rand"), ("South Sudan", "Juba", "Pound"),
        ("Spain", "Madrid", "Euro"), ("Sri Lanka", "Sri Jayawardenepura", "Rupee"), ("Sudan", "Khartoum", "Pound"),
        ("Suriname", "Paramaribo", "Dollar"), ("Sweden", "Stockholm", "Krona"), ("Switzerland", "Bern", "Franc"),
        ("Syria", "Damascus", "Pound"), ("Taiwan", "Taipei", "Dollar"), ("Tajikistan", "Dushanbe", "Somoni"),
        ("Tanzania", "Dodoma", "Shilling"), ("Thailand", "Bangkok", "Baht"), ("Timor-Leste", "Dili", "Dollar"),
        ("Togo", "Lome", "Franc"), ("Tonga", "Nuku'alofa", "Pa'anga"), ("Trinidad and Tobago", "Port of Spain", "Dollar"),
        ("Tunisia", "Tunis", "Dinar"), ("Turkey", "Ankara", "Lira"), ("Turkmenistan", "Ashgabat", "Manat"),
        ("Tuvalu", "Funafuti", "Dollar"), ("Uganda", "Kampala", "Shilling"), ("Ukraine", "Kyiv", "Hryvnia"),
        ("United Arab Emirates", "Abu Dhabi", "Dirham"), ("United Kingdom", "London", "Pound"), ("United States", "Washington D.C.", "Dollar"),
        ("Uruguay", "Montevideo", "Peso"), ("Uzbekistan", "Tashkent", "Som"), ("Vanuatu", "Port Vila", "Vatu"),
        ("Vatican City", "Vatican City", "Euro"), ("Venezuela", "Caracas", "Bolivar"), ("Vietnam", "Hanoi", "Dong"),
        ("Yemen", "Sanaa", "Rial"), ("Zambia", "Lusaka", "Kwacha"), ("Zimbabwe", "Harare", "Dollar"),
    ]
    name, capital, currency = random.choice(countries)
    return "Country: {} | Capital: {} | Currency: {}".format(name, capital, currency)

def country_by_continent():
    data = {
        "Asia": ["China","India","Japan","South Korea","Indonesia","Thailand","Vietnam","Philippines","Malaysia","Singapore","Myanmar","Bangladesh","Pakistan","Sri Lanka","Nepal","Bhutan","Maldives","Brunei","Cambodia","Laos","Mongolia","Taiwan","Afghanistan","Iran","Iraq","Israel","Jordan","Kuwait","Lebanon","Oman","Qatar","Saudi Arabia","Syria","Turkey","United Arab Emirates","Yemen","Armenia","Azerbaijan","Bahrain","Cyprus","Georgia","Kazakhstan","Kyrgyzstan","Russia","Tajikistan","Turkmenistan","Uzbekistan","Palestine"],
        "Africa": ["Nigeria","Ethiopia","Egypt","South Africa","Kenya","Algeria","Sudan","Morocco","Angola","Mozambique","Ghana","Cameroon","Ivory Coast","Niger","Burkina Faso","Mali","Malawi","Zambia","Senegal","Chad","Somalia","Zimbabwe","Guinea","Rwanda","Benin","Burundi","Tunisia","South Sudan","Togo","Libya","Sierra Leone","Eritrea","Central African Republic","Congo","Liberia","Mauritania","Botswana","Lesotho","Namibia","Gabon","Equatorial Guinea","Mauritius","Eswatini","Djibouti","Comoros","Seychelles","Cabo Verde","Sao Tome and Principe","Gambia"],
        "Europe": ["Russia","Germany","United Kingdom","France","Italy","Spain","Ukraine","Poland","Romania","Netherlands","Belgium","Czech Republic","Greece","Portugal","Sweden","Hungary","Austria","Switzerland","Bulgaria","Denmark","Finland","Slovakia","Norway","Ireland","Croatia","Moldova","Bosnia","Albania","Lithuania","Slovenia","North Macedonia","Latvia","Estonia","Montenegro","Luxembourg","Malta","Iceland","Andorra","Monaco","Liechtenstein","San Marino","Vatican City","Serbia","Belarus","Kosovo"],
        "Americas": ["United States","Brazil","Mexico","Colombia","Argentina","Canada","Peru","Venezuela","Chile","Guatemala","Ecuador","Bolivia","Haiti","Dominican Republic","Cuba","Honduras","Paraguay","Nicaragua","El Salvador","Costa Rica","Panama","Uruguay","Jamaica","Trinidad and Tobago","Guyana","Suriname","Belize","Bahamas","Barbados","Saint Lucia","Grenada","Saint Vincent","Antigua and Barbuda","Dominica","Saint Kitts and Nevis"],
        "Oceania": ["Australia","Papua New Guinea","New Zealand","Fiji","Solomon Islands","Vanuatu","Samoa","Kiribati","Micronesia","Tonga","Marshall Islands","Palau","Tuvalu","Nauru"],
    }
    continent = random.choice(list(data.keys()))
    country = random.choice(data[continent])
    return "{} is in {}".format(country, continent)

def world_population():
    pops = [
        ("China", 1425), ("India", 1428), ("USA", 340), ("Indonesia", 278), ("Pakistan", 240),
        ("Nigeria", 223), ("Brazil", 216), ("Bangladesh", 173), ("Russia", 144), ("Mexico", 129),
        ("Ethiopia", 126), ("Japan", 124), ("Philippines", 117), ("Egypt", 112), ("DR Congo", 102),
        ("Vietnam", 99), ("Iran", 89), ("Turkey", 85), ("Germany", 83), ("Thailand", 72),
        ("United Kingdom", 68), ("Tanzania", 65), ("France", 65), ("South Africa", 60),
        ("Italy", 59), ("Kenya", 55), ("Myanmar", 54), ("Colombia", 52), ("South Korea", 52),
        ("Uganda", 50), ("Spain", 47), ("Argentina", 46), ("Algeria", 45), ("Sudan", 45),
        ("Ukraine", 44), ("Iraq", 44), ("Afghanistan", 42), ("Poland", 38), ("Canada", 38),
        ("Morocco", 37), ("Saudi Arabia", 36), ("Angola", 36), ("Uzbekistan", 35),
        ("Yemen", 35), ("Peru", 34), ("Mozambique", 33), ("Ghana", 33), ("Nepal", 31),
        ("Madagascar", 31), ("Malaysia", 34), ("Cameroon", 29), ("Ivory Coast", 29),
        ("Venezuela", 29), ("Niger", 28), ("Australia", 26), ("North Korea", 26),
        ("Taiwan", 24), ("Burkina Faso", 23), ("Mali", 23), ("Syria", 23), ("Sri Lanka", 22),
        ("Malawi", 21), ("Zambia", 21), ("Kazakhstan", 20), ("Chad", 19), ("Chile", 20),
        ("Romania", 19), ("Somalia", 18), ("Senegal", 18), ("Guatemala", 18),
        ("Netherlands", 18), ("Ecuador", 18), ("Cambodia", 17), ("Zimbabwe", 17),
        ("Guinea", 14), ("Rwanda", 14), ("Benin", 14), ("Burundi", 13), ("Tunisia", 12),
        ("Bolivia", 12), ("Belgium", 12), ("Haiti", 12), ("South Sudan", 12),
        ("Cuba", 11), ("Dominican Republic", 11), ("Czech Republic", 11), ("Greece", 10),
        ("Jordan", 11), ("Portugal", 10), ("Azerbaijan", 10), ("Sweden", 10),
        ("Honduras", 10), ("United Arab Emirates", 10), ("Hungary", 10), ("Tajikistan", 10),
        ("Belarus", 9), ("Austria", 9), ("Papua New Guinea", 9),
        ("Switzerland", 9), ("Israel", 9), ("Togo", 9), ("Sierra Leone", 9),
        ("Hong Kong", 7), ("Laos", 8), ("Paraguay", 7), ("Bulgaria", 7),
        ("Libya", 7), ("Lebanon", 5), ("Nicaragua", 7), ("Kyrgyzstan", 7),
        ("El Salvador", 6), ("Turkmenistan", 6), ("Singapore", 6), ("Denmark", 6),
        ("Finland", 6), ("Congo", 6), ("Slovakia", 5), ("Norway", 5),
        ("Eritrea", 4), ("Palestine", 5), ("Costa Rica", 5), ("New Zealand", 5),
        ("Ireland", 5), ("Central African Republic", 5), ("Oman", 5), ("Kuwait", 5),
        ("Panama", 4), ("Mauritania", 5), ("Croatia", 4), ("Georgia", 4),
        ("Uruguay", 3), ("Mongolia", 3), ("Bosnia", 3), ("Qatar", 3), ("Puerto Rico", 3),
        ("Moldova", 3), ("Armenia", 3), ("Lithuania", 3), ("Albania", 3),
        ("Jamaica", 3), ("Namibia", 3), ("Gambia", 3), ("Botswana", 3),
        ("Gabon", 2), ("Lesotho", 2), ("Slovenia", 2), ("Latvia", 2),
        ("North Macedonia", 2), ("Guinea-Bissau", 2), ("Bahrain", 2),
        ("Trinidad and Tobago", 2), ("Estonia", 1), ("Timor-Leste", 1),
        ("Mauritius", 1), ("Cyprus", 1), ("Eswatini", 1), ("Djibouti", 1),
        ("Fiji", 1), ("Comoros", 1), ("Guyana", 1), ("Bhutan", 1),
        ("Solomon Islands", 1), ("Luxembourg", 1), ("Montenegro", 1),
        ("Suriname", 1), ("Malta", 1), ("Maldives", 0.5), ("Cabo Verde", 0.6),
        ("Brunei", 0.4), ("Belize", 0.4), ("Bahamas", 0.4), ("Iceland", 0.4),
        ("Vanuatu", 0.3), ("Barbados", 0.3), ("Samoa", 0.2), ("Saint Lucia", 0.2),
        ("Kiribati", 0.1), ("Seychelles", 0.1), ("Grenada", 0.1),
        ("Tonga", 0.1), ("Saint Vincent", 0.1), ("Micronesia", 0.1),
        ("Antigua and Barbuda", 0.1), ("Andorra", 0.08), ("Dominica", 0.07),
        ("Marshall Islands", 0.04), ("Liechtenstein", 0.04), ("Monaco", 0.04),
        ("San Marino", 0.03), ("Palau", 0.02), ("Tuvalu", 0.01), ("Nauru", 0.01),
        ("Vatican City", 0.001),
    ]
    name, pop = random.choice(pops)
    return "{}: {} million".format(name, pop)

def largest_cities():
    cities = [
        ("Tokyo", 37.4), ("Delhi", 32.9), ("Shanghai", 29.2), ("Sao Paulo", 22.4),
        ("Mumbai", 22.1), ("Beijing", 21.5), ("Cairo", 21.3), ("Dhaka", 21.0),
        ("Mexico City", 20.1), ("Osaka", 19.2), ("Karachi", 18.0), ("Chongqing", 17.8),
        ("Istanbul", 15.8), ("Buenos Aires", 15.5), ("Kolkata", 15.3),
        ("Lagos", 15.2), ("Manila", 14.5), ("Tianjin", 14.2), ("Guangzhou", 14.0),
        ("Rio de Janeiro", 13.7), ("Lahore", 13.5), ("Bangalore", 13.2),
        ("Moscow", 12.7), ("Shenzhen", 12.5), ("Chengdu", 12.4),
        ("Paris", 11.1), ("London", 10.8), ("Jakarta", 10.8), ("Nagoya", 10.5),
        ("Lima", 10.4), ("Chicago", 9.4), ("Bogota", 9.3), ("Kinshasa", 9.1),
        ("Tehran", 8.9), ("Santiago", 8.5), ("Ho Chi Minh City", 8.4),
        ("Bangkok", 8.3), ("Hyderabad", 8.2), ("Ahmedabad", 8.1), ("Madrid", 7.9),
        ("Ahmedabad", 8.1), ("Riyadh", 7.8), ("Singapore", 7.7), ("Toronto", 7.6),
        ("Washington D.C.", 7.4), ("Berlin", 7.3), ("Los Angeles", 7.2),
        ("Miami", 7.1), ("Dallas", 7.0), ("Philadelphia", 6.8), ("Atlanta", 6.7),
        ("Houston", 6.6), ("Boston", 6.5), ("San Francisco", 6.4),
        ("Phoenix", 6.3), ("Seattle", 6.2), ("Montreal", 6.1),
        ("Detroit", 6.0), ("Minneapolis", 5.9), ("San Diego", 5.8),
        ("Tampa", 5.7), ("Denver", 5.6), ("St. Louis", 5.4), ("Baltimore", 5.3),
        ("Portland", 5.2), ("Sacramento", 5.1), ("Orlando", 5.0),
        ("San Antonio", 4.9), ("Pittsburgh", 4.8), ("Cincinnati", 4.7),
        ("Las Vegas", 4.6), ("Kansas City", 4.5), ("Columbus", 4.4),
        ("Cleveland", 4.3), ("Indianapolis", 4.2), ("Nashville", 4.1),
        ("Austin", 4.0), ("Milwaukee", 3.9), ("Raleigh", 3.8),
        ("Jacksonville", 3.7), ("Memphis", 3.6), ("Louisville", 3.5),
        ("Richmond", 3.4), ("New Orleans", 3.3), ("Hartford", 3.2),
        ("Buffalo", 3.1), ("Birmingham", 3.0), ("Rochester", 2.9),
        ("Albany", 2.8), ("Albuquerque", 2.7), ("Tucson", 2.6),
        ("Fresno", 2.5), ("Tulsa", 2.4), ("Wichita", 2.3), ("Honolulu", 2.2),
        ("Virginia Beach", 2.1), ("Colorado Springs", 2.0),
        ("Omaha", 1.9), ("Long Beach", 1.8), ("Oakland", 1.7),
        ("Miami Beach", 1.6), ("Santa Ana", 1.5), ("Anaheim", 1.4),
        ("Tampa Bay", 1.3), ("Cape Coral", 1.2), ("Bakersfield", 1.1),
        ("Stockton", 1.0), ("Corpus Christi", 0.9),
    ]
    name, pop = random.choice(cities)
    return "{}: {} million".format(name, pop)

def world_rivers():
    rivers = [
        ("Nile", 6650, "Africa"), ("Amazon", 6400, "South America"), ("Yangtze", 6300, "Asia"),
        ("Mississippi-Missouri", 6275, "North America"), ("Yenisei", 5539, "Asia"),
        ("Yellow River", 5464, "Asia"), ("Ob-Irtysh", 5410, "Asia"), ("Parana", 4880, "South America"),
        ("Congo", 4700, "Africa"), ("Amur", 4444, "Asia"), ("Lena", 4400, "Asia"),
        ("Mekong", 4350, "Asia"), ("Mackenzie", 4241, "North America"), ("Niger", 4180, "Africa"),
        ("Volga", 3645, "Europe"), ("Madeira", 3380, "South America"), ("Indus", 3180, "Asia"),
        ("Yukon", 3185, "North America"), ("Sao Francisco", 2914, "South America"),
        ("Danube", 2850, "Europe"), ("Brahmaputra", 2900, "Asia"), ("Salween", 2815, "Asia"),
        ("Rio Grande", 3051, "North America"), ("Euphrates", 2800, "Asia"), ("Tigris", 1950, "Asia"),
        ("Ganges", 2525, "Asia"), ("Murray-Darling", 2508, "Australia"), ("Don", 1870, "Europe"),
        ("Dnieper", 2201, "Europe"), ("Ural", 2428, "Asia"), ("Zambezi", 2574, "Africa"),
        ("Orinoco", 2140, "South America"), ("Kolyma", 2129, "Asia"), ("Indigirka", 1726, "Asia"),
        ("Shatt al-Arab", 193, "Asia"), ("Jordan", 251, "Asia"), ("Thames", 346, "Europe"),
        ("Seine", 776, "Europe"), ("Rhine", 1320, "Europe"), ("Po", 682, "Europe"),
        ("Tiber", 406, "Europe"), ("Loire", 1012, "Europe"), ("Elbe", 1094, "Europe"),
        ("Oder", 854, "Europe"), ("Vistula", 1047, "Europe"), ("Tagus", 1038, "Europe"),
        ("Ebro", 930, "Europe"), ("Douro", 897, "Europe"), ("Garonne", 647, "Europe"),
        ("Dniester", 1362, "Europe"), ("Pechora", 1809, "Europe"), ("Northern Dvina", 1310, "Europe"),
    ]
    name, length, continent = random.choice(rivers)
    return "River: {} | Length: {} km | Continent: {}".format(name, length, continent)

def world_mountains():
    mountains = [
        ("Everest", 8848, "Nepal/Tibet"), ("K2", 8611, "Pakistan/China"), ("Kangchenjunga", 8586, "Nepal/India"),
        ("Lhotse", 8516, "Nepal/Tibet"), ("Makalu", 8485, "Nepal/Tibet"), ("Cho Oyu", 8188, "Nepal/Tibet"),
        ("Dhaulagiri", 8167, "Nepal"), ("Manaslu", 8163, "Nepal"), ("Nanga Parbat", 8126, "Pakistan"),
        ("Annapurna", 8091, "Nepal"), ("Gasherbrum I", 8080, "Pakistan/China"), ("Broad Peak", 8051, "Pakistan/China"),
        ("Gasherbrum II", 8035, "Pakistan/China"), ("Shishapangma", 8027, "Tibet"), ("Gyachung Kang", 7952, "Nepal/Tibet"),
        ("Aconcagua", 6961, "Argentina"), ("Ojos del Salado", 6893, "Chile/Argentina"),
        ("Mount Kilimanjaro", 5895, "Tanzania"), ("Mount Elbrus", 5642, "Russia"),
        ("Mount Blanc", 4807, "France/Italy"), ("Mount Vinson", 4892, "Antarctica"),
        ("Puncak Jaya", 4884, "Indonesia"), ("Mount Kosciuszko", 2228, "Australia"),
        ("Mount Fuji", 3776, "Japan"), ("Mount Rainier", 4392, "USA"),
        ("Mount Whitney", 4421, "USA"), ("Mount Denali", 6190, "USA"),
        ("Mount Logan", 5959, "Canada"), ("Mount Olympus", 2917, "Greece"),
        ("Mount Vesuvius", 1281, "Italy"), ("Mount Etna", 3329, "Italy"),
        ("Mount Ararat", 5137, "Turkey"), ("Mount Sinai", 2285, "Egypt"),
        ("Table Mountain", 1085, "South Africa"), ("Mount Cook", 3724, "New Zealand"),
        ("Mount Matterhorn", 4478, "Switzerland/Italy"), ("Mount Eiger", 3970, "Switzerland"),
        ("Mount Jungfrau", 4158, "Switzerland"), ("Mount Cervino", 4478, "Italy/Switzerland"),
        ("Mount Huangshan", 1864, "China"), ("Mount Fujiyama", 3776, "Japan"),
        ("Mount Kinabalu", 4095, "Malaysia"), ("Mount Mayon", 2462, "Philippines"),
        ("Mount Pinatubo", 1486, "Philippines"), ("Mount Krakatoa", 813, "Indonesia"),
        ("Mount Toba", 2157, "Indonesia"), ("Mount Bromo", 2329, "Indonesia"),
        ("Mount Semeru", 3676, "Indonesia"), ("Mount Rinjani", 3726, "Indonesia"),
        ("Mount Agung", 3031, "Indonesia"), ("Mount Batur", 1717, "Indonesia"),
        ("Mount Merapi", 2968, "Indonesia"), ("Mount Damavand", 5610, "Iran"),
        ("Mount Chimborazo", 6263, "Ecuador"), ("Mount Cotopaxi", 5897, "Ecuador"),
        ("Mount Cayambe", 5790, "Ecuador"), ("Mount Illiniza", 5248, "Ecuador"),
    ]
    name, height, location = random.choice(mountains)
    return "Mountain: {} | Height: {} m | Location: {}".format(name, height, location)

def world_deserts():
    deserts = [
        ("Antarctica Desert", 14.0, "Antarctica"), ("Arctic Desert", 13.9, "Arctic"),
        ("Sahara Desert", 9.2, "Africa"), ("Arabian Desert", 2.3, "Middle East"),
        ("Gobi Desert", 1.3, "Asia"), ("Patagonian Desert", 0.67, "South America"),
        ("Great Victoria Desert", 0.65, "Australia"), ("Kalahari Desert", 0.56, "Africa"),
        ("Great Basin Desert", 0.49, "North America"), ("Syrian Desert", 0.50, "Middle East"),
        ("Chihuahuan Desert", 0.45, "North America"), ("Karakum Desert", 0.35, "Asia"),
        ("Colorado Plateau", 0.34, "North America"), ("Sonoran Desert", 0.31, "North America"),
        ("Kyzyldesert", 0.30, "Asia"), ("Taklamakan Desert", 0.27, "Asia"),
        ("Thar Desert", 0.20, "Asia"), ("Dasht-e Lut", 0.17, "Iran"),
        ("Dasht-e Kavir", 0.15, "Iran"), ("Namib Desert", 0.08, "Africa"),
        ("Dasht-e Margo", 0.15, "Afghanistan"), ("Registan Desert", 0.15, "Afghanistan"),
        ("Atacama Desert", 0.10, "South America"), ("Guban Desert", 0.07, "Somalia"),
        ("Mojave Desert", 0.06, "North America"), ("Colorado Desert", 0.04, "North America"),
        ("Little Sandy Desert", 0.11, "Australia"), ("Simpson Desert", 0.18, "Australia"),
        ("Sturt Stony Desert", 0.03, "Australia"), ("Tanami Desert", 0.18, "Australia"),
        ("Great Sandy Desert", 0.28, "Australia"), ("Gibson Desert", 0.16, "Australia"),
        ("Painted Desert", 0.01, "North America"), ("Negev Desert", 0.01, "Israel"),
        ("Sinai Desert", 0.06, "Egypt"), ("Judean Desert", 0.00, "Israel"),
    ]
    name, area, location = random.choice(deserts)
    return "Desert: {} | Area: {} million sq km | Location: {}".format(name, area, location)

def world_islands():
    islands = [
        ("Greenland", 2130800, "Denmark"), ("New Guinea", 785753, "Indonesia/Papua New Guinea"),
        ("Borneo", 748168, "Indonesia/Malaysia/Brunei"), ("Madagascar", 587713, "Madagascar"),
        ("Baffin Island", 507451, "Canada"), ("Sumatra", 443066, "Indonesia"),
        ("Honshu", 225800, "Japan"), ("Victoria Island", 217291, "Canada"),
        ("Great Britain", 209331, "United Kingdom"), ("Ellesmere Island", 196236, "Canada"),
        ("Sulawesi", 180681, "Indonesia"), ("South Island", 150437, "New Zealand"),
        ("Java", 138794, "Indonesia"), ("North Island", 113729, "New Zealand"),
        ("Luzon", 109965, "Philippines"), ("Newfoundland", 108860, "Canada"),
        ("Cuba", 105806, "Cuba"), ("Iceland", 103000, "Iceland"),
        ("Mindanao", 97530, "Philippines"), ("Ireland", 84421, "Ireland/UK"),
        ("Hokkaido", 83456, "Japan"), ("Sakhalin", 78100, "Russia"),
        ("Hispaniola", 76192, "Dominican Republic/Haiti"), ("Banks Island", 70028, "Canada"),
        ("Tasmania", 68401, "Australia"), ("Sri Lanka", 65610, "Sri Lanka"),
        ("Devon Island", 55247, "Canada"), ("Kyushu", 36782, "Japan"),
        ("Taiwan", 36193, "Taiwan"), ("New Britain", 35145, "Papua New Guinea"),
        ("Prince of Wales Island", 33339, "Canada"), ("Sonsorol", 32000, "Canada"),
        ("Vancouver Island", 31285, "Canada"), ("Timor", 30777, "Indonesia/East Timor"),
        ("Sicily", 25711, "Italy"), ("Sardinia", 24090, "Italy"),
        ("Somerset Island", 24786, "Canada"), ("Kotelny Island", 23165, "Russia"),
        ("Bali", 5780, "Indonesia"), ("Cyprus", 9251, "Cyprus"),
        ("Corsica", 8681, "France"), ("Crete", 8336, "Greece"),
        ("Antarctica", 14000000, "Antarctica"), ("Hawaii", 10430, "USA"),
        ("Puerto Rico", 9104, "USA"), ("Fiji", 18333, "Fiji"),
        ("Bahamas", 13943, "Bahamas"), ("Maldives", 298, "Maldives"),
        ("Malta", 316, "Malta"), ("Bermuda", 54, "UK"),
        ("Guam", 544, "USA"), ("Barbados", 430, "Barbados"),
        ("Saint Lucia", 616, "Saint Lucia"), ("Grenada", 344, "Grenada"),
        ("Jamaica", 10991, "Jamaica"), ("Trinidad", 4828, "Trinidad and Tobago"),
    ]
    name, area, country = random.choice(islands)
    return "Island: {} | Area: {} sq km | Country: {}".format(name, area, country)

def world_lakes():
    lakes = [
        ("Caspian Sea", 371000, "Asia/Europe"), ("Superior", 82100, "North America"),
        ("Victoria", 68870, "Africa"), ("Huron", 59600, "North America"),
        ("Michigan", 58000, "North America"), ("Tanganyika", 32890, "Africa"),
        ("Baikal", 31500, "Russia"), ("Great Bear", 31080, "Canada"),
        ("Malawi", 29500, "Africa"), ("Great Slave", 28700, "Canada"),
        ("Erie", 25700, "North America"), ("Winnipeg", 24387, "Canada"),
        ("Ontario", 19600, "North America"), ("Ladoga", 17700, "Russia"),
        ("Balkhash", 16400, "Kazakhstan"), ("Onega", 9700, "Russia"),
        ("Titicaca", 8372, "Peru/Bolivia"), ("Nicaragua", 8264, "Nicaragua"),
        ("Athabasca", 7935, "Canada"), ("Titicaca", 8372, "Peru/Bolivia"),
        ("Dead Sea", 605, "Israel/Jordan"), ("Crater Lake", 53, "USA"),
        ("Lake Chad", 1350, "Africa"), ("Lake Tahoe", 491, "USA"),
        ("Lake Como", 146, "Italy"), ("Lake Geneva", 580, "Switzerland/France"),
        ("Lake Garda", 370, "Italy"), ("Lake Lucerne", 114, "Switzerland"),
        ("Lake Zurich", 88, "Switzerland"), ("Lake Maggiore", 212, "Italy/Switzerland"),
        ("Lake Balaton", 592, "Hungary"), ("Lake Peipus", 3555, "Estonia/Russia"),
        ("Lake Van", 3755, "Turkey"), ("Lake Urmia", 6000, "Iran"),
        ("Lake Issyk-Kul", 6236, "Kyrgyzstan"), ("Lake Khanka", 4070, "Russia/China"),
        ("Lake Tana", 3500, "Ethiopia"), ("Lake Turkana", 6405, "Kenya"),
        ("Lake Albert", 5300, "Uganda/Congo"), ("Lake Edward", 2325, "Uganda/Congo"),
        ("Lake Kivu", 2700, "Rwanda/Congo"), ("Lake Mweru", 5120, "Zambia/Congo"),
        ("Lake Bangweulu", 15000, "Zambia"), ("Lake Rukwa", 2600, "Tanzania"),
        ("Lake Eyasi", 1050, "Tanzania"), ("Lake Natron", 800, "Tanzania"),
        ("Lake Manyara", 470, "Tanzania"), ("Lake Nakuru", 52, "Kenya"),
        ("Lake Bogoria", 30, "Kenya"), ("Lake Baringo", 130, "Kenya"),
    ]
    name, area, location = random.choice(lakes)
    return "Lake: {} | Area: {} sq km | Location: {}".format(name, area, location)

def world_wonders():
    wonders = [
        ("Great Pyramid of Giza", "Egypt", "2560 BC"), ("Hanging Gardens of Babylon", "Iraq", "600 BC"),
        ("Statue of Zeus at Olympia", "Greece", "435 BC"), ("Temple of Artemis at Ephesus", "Turkey", "550 BC"),
        ("Mausoleum at Halicarnassus", "Turkey", "350 BC"), ("Colossus of Rhodes", "Greece", "280 BC"),
        ("Lighthouse of Alexandria", "Egypt", "280 BC"), ("Great Wall of China", "China", "700 BC"),
        ("Petra", "Jordan", "300 BC"), ("Christ the Redeemer", "Brazil", "1931"),
        ("Machu Picchu", "Peru", "1450"), ("Chichen Itza", "Mexico", "600"),
        ("Roman Colosseum", "Italy", "80"), ("Taj Mahal", "India", "1648"),
        ("Angkor Wat", "Cambodia", "1150"), ("Acropolis of Athens", "Greece", "438 BC"),
        ("Stonehenge", "UK", "2500 BC"), ("Moai Statues", "Chile", "1250"),
        ("Colosseum", "Italy", "80"), ("Leaning Tower of Pisa", "Italy", "1372"),
        ("Eiffel Tower", "France", "1889"), ("Statue of Liberty", "USA", "1886"),
        ("Sydney Opera House", "Australia", "1973"), ("Burj Khalifa", "UAE", "2010"),
        ("St. Peter's Basilica", "Vatican City", "1626"), ("Notre Dame", "France", "1345"),
        ("Sagrada Familia", "Spain", "1882 ongoing"), ("Golden Gate Bridge", "USA", "1937"),
        ("Niagara Falls", "Canada/USA", "Natural"), ("Grand Canyon", "USA", "Natural"),
        ("Great Barrier Reef", "Australia", "Natural"), ("Mount Everest", "Nepal/Tibet", "Natural"),
        ("Amazon Rainforest", "South America", "Natural"), ("Victoria Falls", "Zambia/Zimbabwe", "Natural"),
        ("Northern Lights", "Arctic", "Natural"), ("Paricutin Volcano", "Mexico", "1943"),
        ("Harbor of Rio de Janeiro", "Brazil", "Natural"), ("Ha Long Bay", "Vietnam", "Natural"),
        ("Iguazu Falls", "Argentina/Brazil", "Natural"), ("Jeju Island", "South Korea", "Natural"),
        ("Komodo Island", "Indonesia", "Natural"), ("Maldives", "Maldives", "Natural"),
        ("Mount Fuji", "Japan", "Natural"), ("Plitvice Lakes", "Croatia", "Natural"),
        ("Table Mountain", "South Africa", "Natural"), ("Yellowstone", "USA", "Natural"),
    ]
    name, location, year = random.choice(wonders)
    return "Wonder: {} | Location: {} | Date: {}".format(name, location, year)

def world_currencies():
    all_currencies = [
        ("US Dollar", "$", "USD"), ("Euro", "\u20ac", "EUR"), ("British Pound", "\u00a3", "GBP"),
        ("Japanese Yen", "\u00a5", "JPY"), ("Indian Rupee", "\u20b9", "INR"), ("Chinese Yuan", "\u00a5", "CNY"),
        ("Russian Ruble", "\u0440\u0443\u0431", "RUB"), ("Canadian Dollar", "C$", "CAD"),
        ("Australian Dollar", "A$", "AUD"), ("Swiss Franc", "CHF", "CHF"),
        ("Brazilian Real", "R$", "BRL"), ("Mexican Peso", "Mex$", "MXN"),
        ("South Korean Won", "\u20a9", "KRW"), ("Swedish Krona", "kr", "SEK"),
        ("Norwegian Krone", "kr", "NOK"), ("Danish Krone", "kr", "DKK"),
        ("New Zealand Dollar", "NZ$", "NZD"), ("Singapore Dollar", "S$", "SGD"),
        ("Hong Kong Dollar", "HK$", "HKD"), ("Thai Baht", "\u0e3f", "THB"),
        ("Turkish Lira", "\u20ba", "TRY"), ("South African Rand", "R", "ZAR"),
        ("Saudi Riyal", "\ufdfc", "SAR"), ("UAE Dirham", "AED", "AED"),
        ("Israeli Shekel", "\u20aa", "ILS"), ("Polish Zloty", "z\u0142", "PLN"),
        ("Czech Koruna", "K\u010d", "CZK"), ("Hungarian Forint", "Ft", "HUF"),
        ("Indonesian Rupiah", "Rp", "IDR"), ("Malaysian Ringgit", "RM", "MYR"),
        ("Philippine Peso", "\u20b1", "PHP"), ("Vietnamese Dong", "\u20ab", "VND"),
        ("Egyptian Pound", "\u00a3", "EGP"), ("Argentine Peso", "AR$", "ARS"),
        ("Colombian Peso", "Col$", "COP"), ("Chilean Peso", "CL$", "CLP"),
        ("Peruvian Sol", "S/", "PEN"), ("Kenyan Shilling", "KSh", "KES"),
        ("Nigerian Naira", "\u20a6", "NGN"), ("Pakistani Rupee", "\u20a8", "PKR"),
        ("Bangladeshi Taka", "\u09f3", "BDT"), ("Kuwaiti Dinar", "KD", "KWD"),
        ("Qatari Riyal", "QR", "QAR"), ("Omani Rial", "RO", "OMR"),
        ("Bahraini Dinar", "BD", "BHD"), ("Jordanian Dinar", "JD", "JOD"),
        ("Iraqi Dinar", "ID", "IQD"), ("Lebanese Pound", "LL", "LBP"),
        ("Moroccan Dirham", "DH", "MAD"), ("Tunisian Dinar", "DT", "TND"),
        ("Algerian Dinar", "DA", "DZD"), ("Iranian Rial", "IRR", "IRR"),
        ("Afghan Afghani", "AFN", "AFN"), ("Nepalese Rupee", "\u20a8", "NPR"),
        ("Sri Lankan Rupee", "\u20a8", "LKR"), ("Myanmar Kyat", "K", "MMK"),
        ("Cambodian Riel", "\u17db", "KHR"), ("Laotian Kip", "\u20ad", "LAK"),
        ("Mongolian Tugrik", "\u20ae", "MNT"), ("Kazakhstani Tenge", "\u20b8", "KZT"),
        ("Uzbekistani Som", "So'm", "UZS"), ("Turkmen Manat", "TMT", "TMT"),
        ("Georgian Lari", "\u20be", "GEL"), ("Armenian Dram", "\u058f", "AMD"),
        ("Azerbaijani Manat", "\u20bc", "AZN"), ("Ukrainian Hryvnia", "\u20b4", "UAH"),
        ("Belarusian Ruble", "Br", "BYN"), ("Moldovan Leu", "L", "MDL"),
        ("Serbian Dinar", "RSD", "RSD"), ("Croatian Kuna", "kn", "HRK"),
        ("Bosnian Mark", "KM", "BAM"), ("Macedonian Denar", "DEN", "MKD"),
        ("Albanian Lek", "L", "ALL"), ("Bulgarian Lev", "\u043b\u0432", "BGN"),
        ("Romanian Leu", "lei", "RON"), ("Icelandic Krona", "\u00edkr", "ISK"),
        ("Ethiopian Birr", "Br", "ETB"), ("Ghanaian Cedi", "GH\u20b5", "GHS"),
        ("Tanzanian Shilling", "TSh", "TZS"), ("Ugandan Shilling", "USh", "UGX"),
        ("Zambian Kwacha", "ZK", "ZMW"), ("Botswana Pula", "P", "BWP"),
        ("Namibian Dollar", "N$", "NAD"), ("Mauritian Rupee", "\u20a8", "MUR"),
        ("Seychellois Rupee", "\u20a8", "SCR"), ("Fijian Dollar", "FJ$", "FJD"),
        ("Papua New Guinean Kina", "K", "PGK"), ("Solomon Islands Dollar", "SI$", "SBD"),
        ("Vanuatu Vatu", "VT", "VUV"), ("Samoan Tala", "WS$", "WST"),
        ("Tongan Pa'anga", "T$", "TOP"), ("Cuban Peso", "CUP", "CUP"),
        ("Jamaican Dollar", "J$", "JMD"), ("Bahamian Dollar", "B$", "BSD"),
        ("Barbadian Dollar", "Bds$", "BBD"), ("Trinidad and Tobago Dollar", "TT$", "TTD"),
        ("Guyanese Dollar", "GY$", "GYD"), ("Surinamese Dollar", "SR$", "SRD"),
        ("Paraguayan Guarani", "\u20b2", "PYG"), ("Uruguayan Peso", "$U", "UYU"),
        ("Bolivian Boliviano", "Bs", "BOB"), ("Venezuelan Bolivar", "Bs.S", "VES"),
    ]
    name, symbol, code = random.choice(all_currencies)
    return "Currency: {} ({}) - {}".format(name, symbol, code)

def random_flag_description():
    flags = [
        ("Japan", "White rectangle with a red circle in the center"),
        ("France", "Three vertical stripes: blue, white, red"),
        ("Italy", "Three vertical stripes: green, white, red"),
        ("Germany", "Three horizontal stripes: black, red, gold"),
        ("Brazil", "Green with a yellow diamond containing a blue globe"),
        ("India", "Three horizontal stripes: saffron, white, green with a blue wheel"),
        ("Australia", "Blue with Union Jack and six white stars"),
        ("Canada", "Red with a white square containing a red maple leaf"),
        ("China", "Red with one large and four small yellow stars"),
        ("USA", "Red and white stripes with a blue canton of 50 stars"),
        ("Russia", "Three horizontal stripes: white, blue, red"),
        ("United Kingdom", "Blue with red and white crosses (Union Jack)"),
        ("South Africa", "Y-shaped green stripe on red, blue, and black"),
        ("Argentina", "Three horizontal stripes: light blue, white, light blue with a sun"),
        ("Sweden", "Blue with a yellow Scandinavian cross"),
        ("Switzerland", "Red square with a white cross in the center"),
        ("Norway", "Red with a blue Scandinavian cross outlined in white"),
        ("Denmark", "Red with a white Scandinavian cross"),
        ("Finland", "White with a blue Scandinavian cross"),
        ("Iceland", "Blue with a red and white Scandinavian cross"),
        ("Ireland", "Three vertical stripes: green, white, orange"),
        ("Greece", "Blue and white horizontal stripes with a white cross"),
        ("Portugal", "Green and red with a shield and armillary sphere"),
        ("Netherlands", "Three horizontal stripes: red, white, blue"),
        ("Belgium", "Three vertical stripes: black, yellow, red"),
        ("Austria", "Three horizontal stripes: red, white, red"),
        ("Poland", "Two horizontal stripes: white on top, red on bottom"),
        ("Czech Republic", "White and red with a blue triangle on the left"),
        ("Hungary", "Three horizontal stripes: red, white, green"),
        ("Turkey", "Red with a white crescent and star"),
        ("Saudi Arabia", "Green with Arabic inscription and a sword"),
        ("Israel", "White with two blue stripes and a Star of David"),
        ("Egypt", "Three horizontal stripes: red, white, black with an eagle"),
        ("Kenya", "Black, red, green horizontal stripes with white edges and a Maasai shield"),
        ("Nigeria", "Three vertical stripes: green, white, green"),
        ("Mexico", "Three vertical stripes: green, white, red with an eagle on a cactus"),
        ("South Korea", "White with a red/blue yin-yang and four black trigrams"),
        ("Thailand", "Five horizontal stripes: blue, red, white, red, blue"),
        ("Vietnam", "Red with a large yellow star in the center"),
        ("Philippines", "Red, blue, and white with a yellow sun and three stars"),
        ("Indonesia", "Two horizontal stripes: red on top, white on bottom"),
        ("Malaysia", "Red and white stripes with a blue canton and crescent and star"),
        ("Singapore", "Red and white with a crescent and five stars"),
        ("New Zealand", "Blue with Union Jack and four red stars with white borders"),
        ("Chile", "White and red with a blue canton containing a white star"),
        ("Colombia", "Three horizontal stripes: yellow, blue, red"),
        ("Peru", "Three vertical stripes: red, white, red"),
        ("Venezuela", "Three horizontal stripes: yellow, blue, red with an arc of stars"),
        ("Cuba", "Blue and white stripes with a red triangle and white star"),
        ("Morocco", "Red with a green pentagram star in the center"),
    ]
    country, desc = random.choice(flags)
    return "{}: {}".format(country, desc)
